"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from typing import Annotated, Any

from pydantic import Field, StrictBool, StrictFloat, StrictInt, StrictStr, validate_call

from prekit_edge_node_api.api_client import ApiClient, RequestSerialized
from prekit_edge_node_api.api_response import ApiResponse
from prekit_edge_node_api.models.log import Log
from prekit_edge_node_api.models.paginated_log import PaginatedLog
from prekit_edge_node_api.rest import RESTResponseType


class LogApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_all(
        self,
        edge_node_id: Annotated[StrictStr | None, Field(description="Filter by edge node ID")] = None,
        end_time: Annotated[StrictStr | None, Field(description="Filter by end time (ISO format: YYYY-MM-DD HH:MM:SS)")] = None,
        exact_match: Annotated[StrictBool | None, Field(description="Use exact match for logger name (default: false)")] = None,
        function_name: Annotated[StrictStr | None, Field(description="Filter by function name")] = None,
        level: Annotated[StrictStr | None, Field(description="Filter by log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)")] = None,
        logger_name: Annotated[StrictStr | None, Field(description="Filter by logger name (contains match by default)")] = None,
        module_name: Annotated[StrictStr | None, Field(description="Filter by module name")] = None,
        search: Annotated[StrictStr | None, Field(description="Search term to filter results")] = None,
        sort: Annotated[StrictStr | None, Field(description="Sort fields (e.g. '-timestamp,level')")] = None,
        start_time: Annotated[StrictStr | None, Field(description="Filter by start time (ISO format: YYYY-MM-DD HH:MM:SS)")] = None,
        _request_timeout: None | Annotated[StrictFloat, Field(gt=0)] | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> list[Log]:
        """Bulk retrieve consolidated logs

        Fetch complete Docker service logs (infrastructure logs from containers) from all PREKIT microservices. Use with caution for large datasets. NOTE: These are Docker container logs, NOT application signal data. For application signal data, use the metrics endpoints.

        :param edge_node_id: Filter by edge node ID
        :type edge_node_id: str
        :param end_time: Filter by end time (ISO format: YYYY-MM-DD HH:MM:SS)
        :type end_time: str
        :param exact_match: Use exact match for logger name (default: false)
        :type exact_match: bool
        :param function_name: Filter by function name
        :type function_name: str
        :param level: Filter by log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
        :type level: str
        :param logger_name: Filter by logger name (contains match by default)
        :type logger_name: str
        :param module_name: Filter by module name
        :type module_name: str
        :param search: Search term to filter results
        :type search: str
        :param sort: Sort fields (e.g. '-timestamp,level')
        :type sort: str
        :param start_time: Filter by start time (ISO format: YYYY-MM-DD HH:MM:SS)
        :type start_time: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_all_log_serialize(
            edge_node_id=edge_node_id,
            end_time=end_time,
            exact_match=exact_match,
            function_name=function_name,
            level=level,
            logger_name=logger_name,
            module_name=module_name,
            search=search,
            sort=sort,
            start_time=start_time,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: dict[str, str | None] = {
            '200': "List[Log]",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '419': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_all_with_http_info(
        self,
        edge_node_id: Annotated[StrictStr | None, Field(description="Filter by edge node ID")] = None,
        end_time: Annotated[StrictStr | None, Field(description="Filter by end time (ISO format: YYYY-MM-DD HH:MM:SS)")] = None,
        exact_match: Annotated[StrictBool | None, Field(description="Use exact match for logger name (default: false)")] = None,
        function_name: Annotated[StrictStr | None, Field(description="Filter by function name")] = None,
        level: Annotated[StrictStr | None, Field(description="Filter by log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)")] = None,
        logger_name: Annotated[StrictStr | None, Field(description="Filter by logger name (contains match by default)")] = None,
        module_name: Annotated[StrictStr | None, Field(description="Filter by module name")] = None,
        search: Annotated[StrictStr | None, Field(description="Search term to filter results")] = None,
        sort: Annotated[StrictStr | None, Field(description="Sort fields (e.g. '-timestamp,level')")] = None,
        start_time: Annotated[StrictStr | None, Field(description="Filter by start time (ISO format: YYYY-MM-DD HH:MM:SS)")] = None,
        _request_timeout: None | Annotated[StrictFloat, Field(gt=0)] | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[list[Log]]:
        """Bulk retrieve consolidated logs

        Fetch complete Docker service logs (infrastructure logs from containers) from all PREKIT microservices. Use with caution for large datasets. NOTE: These are Docker container logs, NOT application signal data. For application signal data, use the metrics endpoints.

        :param edge_node_id: Filter by edge node ID
        :type edge_node_id: str
        :param end_time: Filter by end time (ISO format: YYYY-MM-DD HH:MM:SS)
        :type end_time: str
        :param exact_match: Use exact match for logger name (default: false)
        :type exact_match: bool
        :param function_name: Filter by function name
        :type function_name: str
        :param level: Filter by log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
        :type level: str
        :param logger_name: Filter by logger name (contains match by default)
        :type logger_name: str
        :param module_name: Filter by module name
        :type module_name: str
        :param search: Search term to filter results
        :type search: str
        :param sort: Sort fields (e.g. '-timestamp,level')
        :type sort: str
        :param start_time: Filter by start time (ISO format: YYYY-MM-DD HH:MM:SS)
        :type start_time: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_all_log_serialize(
            edge_node_id=edge_node_id,
            end_time=end_time,
            exact_match=exact_match,
            function_name=function_name,
            level=level,
            logger_name=logger_name,
            module_name=module_name,
            search=search,
            sort=sort,
            start_time=start_time,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: dict[str, str | None] = {
            '200': "List[Log]",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '419': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_all_without_preload_content(
        self,
        edge_node_id: Annotated[StrictStr | None, Field(description="Filter by edge node ID")] = None,
        end_time: Annotated[StrictStr | None, Field(description="Filter by end time (ISO format: YYYY-MM-DD HH:MM:SS)")] = None,
        exact_match: Annotated[StrictBool | None, Field(description="Use exact match for logger name (default: false)")] = None,
        function_name: Annotated[StrictStr | None, Field(description="Filter by function name")] = None,
        level: Annotated[StrictStr | None, Field(description="Filter by log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)")] = None,
        logger_name: Annotated[StrictStr | None, Field(description="Filter by logger name (contains match by default)")] = None,
        module_name: Annotated[StrictStr | None, Field(description="Filter by module name")] = None,
        search: Annotated[StrictStr | None, Field(description="Search term to filter results")] = None,
        sort: Annotated[StrictStr | None, Field(description="Sort fields (e.g. '-timestamp,level')")] = None,
        start_time: Annotated[StrictStr | None, Field(description="Filter by start time (ISO format: YYYY-MM-DD HH:MM:SS)")] = None,
        _request_timeout: None | Annotated[StrictFloat, Field(gt=0)] | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Bulk retrieve consolidated logs

        Fetch complete Docker service logs (infrastructure logs from containers) from all PREKIT microservices. Use with caution for large datasets. NOTE: These are Docker container logs, NOT application signal data. For application signal data, use the metrics endpoints.

        :param edge_node_id: Filter by edge node ID
        :type edge_node_id: str
        :param end_time: Filter by end time (ISO format: YYYY-MM-DD HH:MM:SS)
        :type end_time: str
        :param exact_match: Use exact match for logger name (default: false)
        :type exact_match: bool
        :param function_name: Filter by function name
        :type function_name: str
        :param level: Filter by log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
        :type level: str
        :param logger_name: Filter by logger name (contains match by default)
        :type logger_name: str
        :param module_name: Filter by module name
        :type module_name: str
        :param search: Search term to filter results
        :type search: str
        :param sort: Sort fields (e.g. '-timestamp,level')
        :type sort: str
        :param start_time: Filter by start time (ISO format: YYYY-MM-DD HH:MM:SS)
        :type start_time: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_all_log_serialize(
            edge_node_id=edge_node_id,
            end_time=end_time,
            exact_match=exact_match,
            function_name=function_name,
            level=level,
            logger_name=logger_name,
            module_name=module_name,
            search=search,
            sort=sort,
            start_time=start_time,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: dict[str, str | None] = {
            '200': "List[Log]",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '419': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_all_log_serialize(
        self,
        edge_node_id,
        end_time,
        exact_match,
        function_name,
        level,
        logger_name,
        module_name,
        search,
        sort,
        start_time,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: dict[str, str] = {
        }

        _path_params: dict[str, str] = {}
        _query_params: list[tuple[str, str]] = []
        _header_params: dict[str, str | None] = _headers or {}
        _form_params: list[tuple[str, str]] = []
        _files: dict[
            str, str | bytes | list[str] | list[bytes] | list[tuple[str, bytes]]
        ] = {}
        _body_params: bytes | None = None

        # process the path parameters
        # process the query parameters
        if edge_node_id is not None:

            _query_params.append(('edge_node_id', edge_node_id))

        if end_time is not None:

            _query_params.append(('end_time', end_time))

        if exact_match is not None:

            _query_params.append(('exact_match', exact_match))

        if function_name is not None:

            _query_params.append(('function_name', function_name))

        if level is not None:

            _query_params.append(('level', level))

        if logger_name is not None:

            _query_params.append(('logger_name', logger_name))

        if module_name is not None:

            _query_params.append(('module_name', module_name))

        if search is not None:

            _query_params.append(('search', search))

        if sort is not None:

            _query_params.append(('sort', sort))

        if start_time is not None:

            _query_params.append(('start_time', start_time))

        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: list[str] = [
            'ApiKeyAuth',
            'OIDC'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v1/historian/logs/',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_one(
        self,
        id: StrictInt,
        _request_timeout: None | Annotated[StrictFloat, Field(gt=0)] | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> Log:
        """Get single log record

        Get a specific Docker service log entry (infrastructure log from containers) from PREKIT microservices by ID. NOTE: This is a Docker container log, NOT application signal data.

        :param id: (required)
        :type id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_one_log_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: dict[str, str | None] = {
            '200': "Log",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '419': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_one_with_http_info(
        self,
        id: StrictInt,
        _request_timeout: None | Annotated[StrictFloat, Field(gt=0)] | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[Log]:
        """Get single log record

        Get a specific Docker service log entry (infrastructure log from containers) from PREKIT microservices by ID. NOTE: This is a Docker container log, NOT application signal data.

        :param id: (required)
        :type id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_one_log_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: dict[str, str | None] = {
            '200': "Log",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '419': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_one_without_preload_content(
        self,
        id: StrictInt,
        _request_timeout: None | Annotated[StrictFloat, Field(gt=0)] | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get single log record

        Get a specific Docker service log entry (infrastructure log from containers) from PREKIT microservices by ID. NOTE: This is a Docker container log, NOT application signal data.

        :param id: (required)
        :type id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_one_log_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: dict[str, str | None] = {
            '200': "Log",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '419': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_one_log_serialize(
        self,
        id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: dict[str, str] = {
        }

        _path_params: dict[str, str] = {}
        _query_params: list[tuple[str, str]] = []
        _header_params: dict[str, str | None] = _headers or {}
        _form_params: list[tuple[str, str]] = []
        _files: dict[
            str, str | bytes | list[str] | list[bytes] | list[tuple[str, bytes]]
        ] = {}
        _body_params: bytes | None = None

        # process the path parameters
        if id is not None:
            _path_params['id'] = id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: list[str] = [
            'ApiKeyAuth',
            'OIDC'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v1/historian/logs/{id}/',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_page(
        self,
        edge_node_id: Annotated[StrictStr | None, Field(description="Filter by edge node ID")] = None,
        end_time: Annotated[StrictStr | None, Field(description="Filter by end time (ISO format: YYYY-MM-DD HH:MM:SS)")] = None,
        exact_match: Annotated[StrictBool | None, Field(description="Use exact match for logger name (default: false)")] = None,
        function_name: Annotated[StrictStr | None, Field(description="Filter by function name")] = None,
        level: Annotated[StrictStr | None, Field(description="Filter by log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)")] = None,
        logger_name: Annotated[StrictStr | None, Field(description="Filter by logger name (contains match by default)")] = None,
        module_name: Annotated[StrictStr | None, Field(description="Filter by module name")] = None,
        page: Annotated[StrictInt | None, Field(description="The page number to retrieve (default 1).")] = None,
        search: Annotated[StrictStr | None, Field(description="Search term to filter results")] = None,
        sort: Annotated[StrictStr | None, Field(description="Sort fields (e.g. '-timestamp,level')")] = None,
        start_time: Annotated[StrictStr | None, Field(description="Filter by start time (ISO format: YYYY-MM-DD HH:MM:SS)")] = None,
        take: Annotated[StrictInt | None, Field(description="The number of items per page (default 10).")] = None,
        _request_timeout: None | Annotated[StrictFloat, Field(gt=0)] | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> PaginatedLog:
        """List consolidated microservice logs

        Retrieve paginated Docker service logs (infrastructure logs from containers) from all PREKIT microservices with filtering by level, logger, module, and time range. NOTE: These are Docker container logs, NOT application signal data. For application signal data, use the metrics endpoints.

        :param edge_node_id: Filter by edge node ID
        :type edge_node_id: str
        :param end_time: Filter by end time (ISO format: YYYY-MM-DD HH:MM:SS)
        :type end_time: str
        :param exact_match: Use exact match for logger name (default: false)
        :type exact_match: bool
        :param function_name: Filter by function name
        :type function_name: str
        :param level: Filter by log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
        :type level: str
        :param logger_name: Filter by logger name (contains match by default)
        :type logger_name: str
        :param module_name: Filter by module name
        :type module_name: str
        :param page: The page number to retrieve (default 1).
        :type page: int
        :param search: Search term to filter results
        :type search: str
        :param sort: Sort fields (e.g. '-timestamp,level')
        :type sort: str
        :param start_time: Filter by start time (ISO format: YYYY-MM-DD HH:MM:SS)
        :type start_time: str
        :param take: The number of items per page (default 10).
        :type take: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_page_log_serialize(
            edge_node_id=edge_node_id,
            end_time=end_time,
            exact_match=exact_match,
            function_name=function_name,
            level=level,
            logger_name=logger_name,
            module_name=module_name,
            page=page,
            search=search,
            sort=sort,
            start_time=start_time,
            take=take,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: dict[str, str | None] = {
            '200': "PaginatedLog",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '419': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_page_with_http_info(
        self,
        edge_node_id: Annotated[StrictStr | None, Field(description="Filter by edge node ID")] = None,
        end_time: Annotated[StrictStr | None, Field(description="Filter by end time (ISO format: YYYY-MM-DD HH:MM:SS)")] = None,
        exact_match: Annotated[StrictBool | None, Field(description="Use exact match for logger name (default: false)")] = None,
        function_name: Annotated[StrictStr | None, Field(description="Filter by function name")] = None,
        level: Annotated[StrictStr | None, Field(description="Filter by log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)")] = None,
        logger_name: Annotated[StrictStr | None, Field(description="Filter by logger name (contains match by default)")] = None,
        module_name: Annotated[StrictStr | None, Field(description="Filter by module name")] = None,
        page: Annotated[StrictInt | None, Field(description="The page number to retrieve (default 1).")] = None,
        search: Annotated[StrictStr | None, Field(description="Search term to filter results")] = None,
        sort: Annotated[StrictStr | None, Field(description="Sort fields (e.g. '-timestamp,level')")] = None,
        start_time: Annotated[StrictStr | None, Field(description="Filter by start time (ISO format: YYYY-MM-DD HH:MM:SS)")] = None,
        take: Annotated[StrictInt | None, Field(description="The number of items per page (default 10).")] = None,
        _request_timeout: None | Annotated[StrictFloat, Field(gt=0)] | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[PaginatedLog]:
        """List consolidated microservice logs

        Retrieve paginated Docker service logs (infrastructure logs from containers) from all PREKIT microservices with filtering by level, logger, module, and time range. NOTE: These are Docker container logs, NOT application signal data. For application signal data, use the metrics endpoints.

        :param edge_node_id: Filter by edge node ID
        :type edge_node_id: str
        :param end_time: Filter by end time (ISO format: YYYY-MM-DD HH:MM:SS)
        :type end_time: str
        :param exact_match: Use exact match for logger name (default: false)
        :type exact_match: bool
        :param function_name: Filter by function name
        :type function_name: str
        :param level: Filter by log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
        :type level: str
        :param logger_name: Filter by logger name (contains match by default)
        :type logger_name: str
        :param module_name: Filter by module name
        :type module_name: str
        :param page: The page number to retrieve (default 1).
        :type page: int
        :param search: Search term to filter results
        :type search: str
        :param sort: Sort fields (e.g. '-timestamp,level')
        :type sort: str
        :param start_time: Filter by start time (ISO format: YYYY-MM-DD HH:MM:SS)
        :type start_time: str
        :param take: The number of items per page (default 10).
        :type take: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_page_log_serialize(
            edge_node_id=edge_node_id,
            end_time=end_time,
            exact_match=exact_match,
            function_name=function_name,
            level=level,
            logger_name=logger_name,
            module_name=module_name,
            page=page,
            search=search,
            sort=sort,
            start_time=start_time,
            take=take,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: dict[str, str | None] = {
            '200': "PaginatedLog",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '419': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_page_without_preload_content(
        self,
        edge_node_id: Annotated[StrictStr | None, Field(description="Filter by edge node ID")] = None,
        end_time: Annotated[StrictStr | None, Field(description="Filter by end time (ISO format: YYYY-MM-DD HH:MM:SS)")] = None,
        exact_match: Annotated[StrictBool | None, Field(description="Use exact match for logger name (default: false)")] = None,
        function_name: Annotated[StrictStr | None, Field(description="Filter by function name")] = None,
        level: Annotated[StrictStr | None, Field(description="Filter by log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)")] = None,
        logger_name: Annotated[StrictStr | None, Field(description="Filter by logger name (contains match by default)")] = None,
        module_name: Annotated[StrictStr | None, Field(description="Filter by module name")] = None,
        page: Annotated[StrictInt | None, Field(description="The page number to retrieve (default 1).")] = None,
        search: Annotated[StrictStr | None, Field(description="Search term to filter results")] = None,
        sort: Annotated[StrictStr | None, Field(description="Sort fields (e.g. '-timestamp,level')")] = None,
        start_time: Annotated[StrictStr | None, Field(description="Filter by start time (ISO format: YYYY-MM-DD HH:MM:SS)")] = None,
        take: Annotated[StrictInt | None, Field(description="The number of items per page (default 10).")] = None,
        _request_timeout: None | Annotated[StrictFloat, Field(gt=0)] | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List consolidated microservice logs

        Retrieve paginated Docker service logs (infrastructure logs from containers) from all PREKIT microservices with filtering by level, logger, module, and time range. NOTE: These are Docker container logs, NOT application signal data. For application signal data, use the metrics endpoints.

        :param edge_node_id: Filter by edge node ID
        :type edge_node_id: str
        :param end_time: Filter by end time (ISO format: YYYY-MM-DD HH:MM:SS)
        :type end_time: str
        :param exact_match: Use exact match for logger name (default: false)
        :type exact_match: bool
        :param function_name: Filter by function name
        :type function_name: str
        :param level: Filter by log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
        :type level: str
        :param logger_name: Filter by logger name (contains match by default)
        :type logger_name: str
        :param module_name: Filter by module name
        :type module_name: str
        :param page: The page number to retrieve (default 1).
        :type page: int
        :param search: Search term to filter results
        :type search: str
        :param sort: Sort fields (e.g. '-timestamp,level')
        :type sort: str
        :param start_time: Filter by start time (ISO format: YYYY-MM-DD HH:MM:SS)
        :type start_time: str
        :param take: The number of items per page (default 10).
        :type take: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_page_log_serialize(
            edge_node_id=edge_node_id,
            end_time=end_time,
            exact_match=exact_match,
            function_name=function_name,
            level=level,
            logger_name=logger_name,
            module_name=module_name,
            page=page,
            search=search,
            sort=sort,
            start_time=start_time,
            take=take,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: dict[str, str | None] = {
            '200': "PaginatedLog",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '419': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_page_log_serialize(
        self,
        edge_node_id,
        end_time,
        exact_match,
        function_name,
        level,
        logger_name,
        module_name,
        page,
        search,
        sort,
        start_time,
        take,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: dict[str, str] = {
        }

        _path_params: dict[str, str] = {}
        _query_params: list[tuple[str, str]] = []
        _header_params: dict[str, str | None] = _headers or {}
        _form_params: list[tuple[str, str]] = []
        _files: dict[
            str, str | bytes | list[str] | list[bytes] | list[tuple[str, bytes]]
        ] = {}
        _body_params: bytes | None = None

        # process the path parameters
        # process the query parameters
        if edge_node_id is not None:

            _query_params.append(('edge_node_id', edge_node_id))

        if end_time is not None:

            _query_params.append(('end_time', end_time))

        if exact_match is not None:

            _query_params.append(('exact_match', exact_match))

        if function_name is not None:

            _query_params.append(('function_name', function_name))

        if level is not None:

            _query_params.append(('level', level))

        if logger_name is not None:

            _query_params.append(('logger_name', logger_name))

        if module_name is not None:

            _query_params.append(('module_name', module_name))

        if page is not None:

            _query_params.append(('page', page))

        if search is not None:

            _query_params.append(('search', search))

        if sort is not None:

            _query_params.append(('sort', sort))

        if start_time is not None:

            _query_params.append(('start_time', start_time))

        if take is not None:

            _query_params.append(('take', take))

        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: list[str] = [
            'ApiKeyAuth',
            'OIDC'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v1/historian/logs/page',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


