"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from typing import Annotated, Any

from pydantic import Field, StrictBool, StrictFloat, StrictInt, StrictStr, validate_call

from prekit_edge_node_api.api_client import ApiClient, RequestSerialized
from prekit_edge_node_api.api_response import ApiResponse
from prekit_edge_node_api.models.metric import Metric
from prekit_edge_node_api.models.paginated_metric import PaginatedMetric
from prekit_edge_node_api.rest import RESTResponseType


class MetricApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_all(
        self,
        end_time: Annotated[StrictStr | None, Field(description="Filter by end time (ISO format: YYYY-MM-DD HH:MM:SS).")] = None,
        filter_by_annotation_types: Annotated[list[StrictStr] | None, Field(description="After selection, restrict to metrics/events that are annotated with these annotation types (array of ULIDs).")] = None,
        select_all: Annotated[StrictBool | None, Field(description="Return all metrics together with annotation-derived events for the filters. When true, 'select_signals' and 'select_annotation_types' must NOT be provided.")] = None,
        select_annotation_types: Annotated[list[StrictStr] | None, Field(description="Include annotation-derived events for these annotation type ULIDs (array).")] = None,
        select_signals: Annotated[list[StrictStr] | None, Field(description="Include metrics/events for these signal ULIDs (array).")] = None,
        select_system_elements: Annotated[list[StrictStr] | None, Field(description="Include metrics/events for all signals belonging to these system elements (array).")] = None,
        sort: Annotated[StrictStr | None, Field(description="Sort fields (e.g. '-timestamp', 'timestamp').")] = None,
        start_time: Annotated[StrictStr | None, Field(description="Filter by start time (ISO format: YYYY-MM-DD HH:MM:SS).")] = None,
        _request_timeout: None | Annotated[StrictFloat, Field(gt=0)] | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> list[Metric]:
        """List time series metrics

        Retrieve paginated ACTUAL HISTORIAN DATA - historicized application signals (sensor readings and logged parameters) mapped to signals.  Selection semantics: - select_signals → metrics for those signals - select_annotation_types → annotation-derived events for those annotation types - select_signals + select_annotation_types → combination of both - select_all → all metrics + all annotation-derived events - filter_by_annotation_types → further restrict to entries annotated with these types

        :param end_time: Filter by end time (ISO format: YYYY-MM-DD HH:MM:SS).
        :type end_time: str
        :param filter_by_annotation_types: After selection, restrict to metrics/events that are annotated with these annotation types (array of ULIDs).
        :type filter_by_annotation_types: List[str]
        :param select_all: Return all metrics together with annotation-derived events for the filters. When true, 'select_signals' and 'select_annotation_types' must NOT be provided.
        :type select_all: bool
        :param select_annotation_types: Include annotation-derived events for these annotation type ULIDs (array).
        :type select_annotation_types: List[str]
        :param select_signals: Include metrics/events for these signal ULIDs (array).
        :type select_signals: List[str]
        :param select_system_elements: Include metrics/events for all signals belonging to these system elements (array).
        :type select_system_elements: List[str]
        :param sort: Sort fields (e.g. '-timestamp', 'timestamp').
        :type sort: str
        :param start_time: Filter by start time (ISO format: YYYY-MM-DD HH:MM:SS).
        :type start_time: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_all_metric_serialize(
            end_time=end_time,
            filter_by_annotation_types=filter_by_annotation_types,
            select_all=select_all,
            select_annotation_types=select_annotation_types,
            select_signals=select_signals,
            select_system_elements=select_system_elements,
            sort=sort,
            start_time=start_time,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: dict[str, str | None] = {
            '200': "List[Metric]",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '419': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_all_with_http_info(
        self,
        end_time: Annotated[StrictStr | None, Field(description="Filter by end time (ISO format: YYYY-MM-DD HH:MM:SS).")] = None,
        filter_by_annotation_types: Annotated[list[StrictStr] | None, Field(description="After selection, restrict to metrics/events that are annotated with these annotation types (array of ULIDs).")] = None,
        select_all: Annotated[StrictBool | None, Field(description="Return all metrics together with annotation-derived events for the filters. When true, 'select_signals' and 'select_annotation_types' must NOT be provided.")] = None,
        select_annotation_types: Annotated[list[StrictStr] | None, Field(description="Include annotation-derived events for these annotation type ULIDs (array).")] = None,
        select_signals: Annotated[list[StrictStr] | None, Field(description="Include metrics/events for these signal ULIDs (array).")] = None,
        select_system_elements: Annotated[list[StrictStr] | None, Field(description="Include metrics/events for all signals belonging to these system elements (array).")] = None,
        sort: Annotated[StrictStr | None, Field(description="Sort fields (e.g. '-timestamp', 'timestamp').")] = None,
        start_time: Annotated[StrictStr | None, Field(description="Filter by start time (ISO format: YYYY-MM-DD HH:MM:SS).")] = None,
        _request_timeout: None | Annotated[StrictFloat, Field(gt=0)] | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[list[Metric]]:
        """List time series metrics

        Retrieve paginated ACTUAL HISTORIAN DATA - historicized application signals (sensor readings and logged parameters) mapped to signals.  Selection semantics: - select_signals → metrics for those signals - select_annotation_types → annotation-derived events for those annotation types - select_signals + select_annotation_types → combination of both - select_all → all metrics + all annotation-derived events - filter_by_annotation_types → further restrict to entries annotated with these types

        :param end_time: Filter by end time (ISO format: YYYY-MM-DD HH:MM:SS).
        :type end_time: str
        :param filter_by_annotation_types: After selection, restrict to metrics/events that are annotated with these annotation types (array of ULIDs).
        :type filter_by_annotation_types: List[str]
        :param select_all: Return all metrics together with annotation-derived events for the filters. When true, 'select_signals' and 'select_annotation_types' must NOT be provided.
        :type select_all: bool
        :param select_annotation_types: Include annotation-derived events for these annotation type ULIDs (array).
        :type select_annotation_types: List[str]
        :param select_signals: Include metrics/events for these signal ULIDs (array).
        :type select_signals: List[str]
        :param select_system_elements: Include metrics/events for all signals belonging to these system elements (array).
        :type select_system_elements: List[str]
        :param sort: Sort fields (e.g. '-timestamp', 'timestamp').
        :type sort: str
        :param start_time: Filter by start time (ISO format: YYYY-MM-DD HH:MM:SS).
        :type start_time: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_all_metric_serialize(
            end_time=end_time,
            filter_by_annotation_types=filter_by_annotation_types,
            select_all=select_all,
            select_annotation_types=select_annotation_types,
            select_signals=select_signals,
            select_system_elements=select_system_elements,
            sort=sort,
            start_time=start_time,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: dict[str, str | None] = {
            '200': "List[Metric]",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '419': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_all_without_preload_content(
        self,
        end_time: Annotated[StrictStr | None, Field(description="Filter by end time (ISO format: YYYY-MM-DD HH:MM:SS).")] = None,
        filter_by_annotation_types: Annotated[list[StrictStr] | None, Field(description="After selection, restrict to metrics/events that are annotated with these annotation types (array of ULIDs).")] = None,
        select_all: Annotated[StrictBool | None, Field(description="Return all metrics together with annotation-derived events for the filters. When true, 'select_signals' and 'select_annotation_types' must NOT be provided.")] = None,
        select_annotation_types: Annotated[list[StrictStr] | None, Field(description="Include annotation-derived events for these annotation type ULIDs (array).")] = None,
        select_signals: Annotated[list[StrictStr] | None, Field(description="Include metrics/events for these signal ULIDs (array).")] = None,
        select_system_elements: Annotated[list[StrictStr] | None, Field(description="Include metrics/events for all signals belonging to these system elements (array).")] = None,
        sort: Annotated[StrictStr | None, Field(description="Sort fields (e.g. '-timestamp', 'timestamp').")] = None,
        start_time: Annotated[StrictStr | None, Field(description="Filter by start time (ISO format: YYYY-MM-DD HH:MM:SS).")] = None,
        _request_timeout: None | Annotated[StrictFloat, Field(gt=0)] | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List time series metrics

        Retrieve paginated ACTUAL HISTORIAN DATA - historicized application signals (sensor readings and logged parameters) mapped to signals.  Selection semantics: - select_signals → metrics for those signals - select_annotation_types → annotation-derived events for those annotation types - select_signals + select_annotation_types → combination of both - select_all → all metrics + all annotation-derived events - filter_by_annotation_types → further restrict to entries annotated with these types

        :param end_time: Filter by end time (ISO format: YYYY-MM-DD HH:MM:SS).
        :type end_time: str
        :param filter_by_annotation_types: After selection, restrict to metrics/events that are annotated with these annotation types (array of ULIDs).
        :type filter_by_annotation_types: List[str]
        :param select_all: Return all metrics together with annotation-derived events for the filters. When true, 'select_signals' and 'select_annotation_types' must NOT be provided.
        :type select_all: bool
        :param select_annotation_types: Include annotation-derived events for these annotation type ULIDs (array).
        :type select_annotation_types: List[str]
        :param select_signals: Include metrics/events for these signal ULIDs (array).
        :type select_signals: List[str]
        :param select_system_elements: Include metrics/events for all signals belonging to these system elements (array).
        :type select_system_elements: List[str]
        :param sort: Sort fields (e.g. '-timestamp', 'timestamp').
        :type sort: str
        :param start_time: Filter by start time (ISO format: YYYY-MM-DD HH:MM:SS).
        :type start_time: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_all_metric_serialize(
            end_time=end_time,
            filter_by_annotation_types=filter_by_annotation_types,
            select_all=select_all,
            select_annotation_types=select_annotation_types,
            select_signals=select_signals,
            select_system_elements=select_system_elements,
            sort=sort,
            start_time=start_time,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: dict[str, str | None] = {
            '200': "List[Metric]",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '419': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_all_metric_serialize(
        self,
        end_time,
        filter_by_annotation_types,
        select_all,
        select_annotation_types,
        select_signals,
        select_system_elements,
        sort,
        start_time,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: dict[str, str] = {
            'filter_by_annotation_types': 'multi',
            'select_annotation_types': 'multi',
            'select_signals': 'multi',
            'select_system_elements': 'multi',
        }

        _path_params: dict[str, str] = {}
        _query_params: list[tuple[str, str]] = []
        _header_params: dict[str, str | None] = _headers or {}
        _form_params: list[tuple[str, str]] = []
        _files: dict[
            str, str | bytes | list[str] | list[bytes] | list[tuple[str, bytes]]
        ] = {}
        _body_params: bytes | None = None

        # process the path parameters
        # process the query parameters
        if end_time is not None:

            _query_params.append(('end_time', end_time))

        if filter_by_annotation_types is not None:

            _query_params.append(('filter_by_annotation_types', filter_by_annotation_types))

        if select_all is not None:

            _query_params.append(('select_all', select_all))

        if select_annotation_types is not None:

            _query_params.append(('select_annotation_types', select_annotation_types))

        if select_signals is not None:

            _query_params.append(('select_signals', select_signals))

        if select_system_elements is not None:

            _query_params.append(('select_system_elements', select_system_elements))

        if sort is not None:

            _query_params.append(('sort', sort))

        if start_time is not None:

            _query_params.append(('start_time', start_time))

        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: list[str] = [
            'ApiKeyAuth',
            'OIDC'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v1/historian/metrics/',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_one(
        self,
        id: StrictInt,
        _request_timeout: None | Annotated[StrictFloat, Field(gt=0)] | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> Metric:
        """Get single metric record

        Get a specific ACTUAL HISTORIAN DATA record - a historicized application signal (sensor reading or logged parameter) by ID. This is application signal data, NOT Docker service logs.

        :param id: (required)
        :type id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_one_metric_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: dict[str, str | None] = {
            '200': "Metric",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '419': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_one_with_http_info(
        self,
        id: StrictInt,
        _request_timeout: None | Annotated[StrictFloat, Field(gt=0)] | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[Metric]:
        """Get single metric record

        Get a specific ACTUAL HISTORIAN DATA record - a historicized application signal (sensor reading or logged parameter) by ID. This is application signal data, NOT Docker service logs.

        :param id: (required)
        :type id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_one_metric_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: dict[str, str | None] = {
            '200': "Metric",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '419': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_one_without_preload_content(
        self,
        id: StrictInt,
        _request_timeout: None | Annotated[StrictFloat, Field(gt=0)] | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get single metric record

        Get a specific ACTUAL HISTORIAN DATA record - a historicized application signal (sensor reading or logged parameter) by ID. This is application signal data, NOT Docker service logs.

        :param id: (required)
        :type id: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_one_metric_serialize(
            id=id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: dict[str, str | None] = {
            '200': "Metric",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '419': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_one_metric_serialize(
        self,
        id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: dict[str, str] = {
        }

        _path_params: dict[str, str] = {}
        _query_params: list[tuple[str, str]] = []
        _header_params: dict[str, str | None] = _headers or {}
        _form_params: list[tuple[str, str]] = []
        _files: dict[
            str, str | bytes | list[str] | list[bytes] | list[tuple[str, bytes]]
        ] = {}
        _body_params: bytes | None = None

        # process the path parameters
        if id is not None:
            _path_params['id'] = id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: list[str] = [
            'ApiKeyAuth',
            'OIDC'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v1/historian/metrics/{id}/',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_page(
        self,
        end_time: Annotated[StrictStr | None, Field(description="Filter by end time (ISO format: YYYY-MM-DD HH:MM:SS).")] = None,
        filter_by_annotation_types: Annotated[list[StrictStr] | None, Field(description="After selection, restrict to metrics/events that are annotated with these annotation types (array of ULIDs).")] = None,
        page: Annotated[StrictInt | None, Field(description="The page number to retrieve (default 1).")] = None,
        select_all: Annotated[StrictBool | None, Field(description="Return all metrics together with annotation-derived events for the filters. When true, 'select_signals' and 'select_annotation_types' must NOT be provided.")] = None,
        select_annotation_types: Annotated[list[StrictStr] | None, Field(description="Include annotation-derived events for these annotation type ULIDs (array).")] = None,
        select_signals: Annotated[list[StrictStr] | None, Field(description="Include metrics/events for these signal ULIDs (array).")] = None,
        select_system_elements: Annotated[list[StrictStr] | None, Field(description="Include metrics/events for all signals belonging to these system elements (array).")] = None,
        sort: Annotated[StrictStr | None, Field(description="Sort fields (e.g. '-timestamp', 'timestamp').")] = None,
        start_time: Annotated[StrictStr | None, Field(description="Filter by start time (ISO format: YYYY-MM-DD HH:MM:SS).")] = None,
        take: Annotated[StrictInt | None, Field(description="The number of items per page (default 10).")] = None,
        _request_timeout: None | Annotated[StrictFloat, Field(gt=0)] | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> PaginatedMetric:
        """List time series metrics

        Retrieve paginated ACTUAL HISTORIAN DATA - historicized application signals (sensor readings and logged parameters) mapped to signals.  Selection semantics: - select_signals → metrics for those signals - select_annotation_types → annotation-derived events for those annotation types - select_signals + select_annotation_types → combination of both - select_all → all metrics + all annotation-derived events - filter_by_annotation_types → further restrict to entries annotated with these types

        :param end_time: Filter by end time (ISO format: YYYY-MM-DD HH:MM:SS).
        :type end_time: str
        :param filter_by_annotation_types: After selection, restrict to metrics/events that are annotated with these annotation types (array of ULIDs).
        :type filter_by_annotation_types: List[str]
        :param page: The page number to retrieve (default 1).
        :type page: int
        :param select_all: Return all metrics together with annotation-derived events for the filters. When true, 'select_signals' and 'select_annotation_types' must NOT be provided.
        :type select_all: bool
        :param select_annotation_types: Include annotation-derived events for these annotation type ULIDs (array).
        :type select_annotation_types: List[str]
        :param select_signals: Include metrics/events for these signal ULIDs (array).
        :type select_signals: List[str]
        :param select_system_elements: Include metrics/events for all signals belonging to these system elements (array).
        :type select_system_elements: List[str]
        :param sort: Sort fields (e.g. '-timestamp', 'timestamp').
        :type sort: str
        :param start_time: Filter by start time (ISO format: YYYY-MM-DD HH:MM:SS).
        :type start_time: str
        :param take: The number of items per page (default 10).
        :type take: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_page_metric_serialize(
            end_time=end_time,
            filter_by_annotation_types=filter_by_annotation_types,
            page=page,
            select_all=select_all,
            select_annotation_types=select_annotation_types,
            select_signals=select_signals,
            select_system_elements=select_system_elements,
            sort=sort,
            start_time=start_time,
            take=take,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: dict[str, str | None] = {
            '200': "PaginatedMetric",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '419': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_page_with_http_info(
        self,
        end_time: Annotated[StrictStr | None, Field(description="Filter by end time (ISO format: YYYY-MM-DD HH:MM:SS).")] = None,
        filter_by_annotation_types: Annotated[list[StrictStr] | None, Field(description="After selection, restrict to metrics/events that are annotated with these annotation types (array of ULIDs).")] = None,
        page: Annotated[StrictInt | None, Field(description="The page number to retrieve (default 1).")] = None,
        select_all: Annotated[StrictBool | None, Field(description="Return all metrics together with annotation-derived events for the filters. When true, 'select_signals' and 'select_annotation_types' must NOT be provided.")] = None,
        select_annotation_types: Annotated[list[StrictStr] | None, Field(description="Include annotation-derived events for these annotation type ULIDs (array).")] = None,
        select_signals: Annotated[list[StrictStr] | None, Field(description="Include metrics/events for these signal ULIDs (array).")] = None,
        select_system_elements: Annotated[list[StrictStr] | None, Field(description="Include metrics/events for all signals belonging to these system elements (array).")] = None,
        sort: Annotated[StrictStr | None, Field(description="Sort fields (e.g. '-timestamp', 'timestamp').")] = None,
        start_time: Annotated[StrictStr | None, Field(description="Filter by start time (ISO format: YYYY-MM-DD HH:MM:SS).")] = None,
        take: Annotated[StrictInt | None, Field(description="The number of items per page (default 10).")] = None,
        _request_timeout: None | Annotated[StrictFloat, Field(gt=0)] | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[PaginatedMetric]:
        """List time series metrics

        Retrieve paginated ACTUAL HISTORIAN DATA - historicized application signals (sensor readings and logged parameters) mapped to signals.  Selection semantics: - select_signals → metrics for those signals - select_annotation_types → annotation-derived events for those annotation types - select_signals + select_annotation_types → combination of both - select_all → all metrics + all annotation-derived events - filter_by_annotation_types → further restrict to entries annotated with these types

        :param end_time: Filter by end time (ISO format: YYYY-MM-DD HH:MM:SS).
        :type end_time: str
        :param filter_by_annotation_types: After selection, restrict to metrics/events that are annotated with these annotation types (array of ULIDs).
        :type filter_by_annotation_types: List[str]
        :param page: The page number to retrieve (default 1).
        :type page: int
        :param select_all: Return all metrics together with annotation-derived events for the filters. When true, 'select_signals' and 'select_annotation_types' must NOT be provided.
        :type select_all: bool
        :param select_annotation_types: Include annotation-derived events for these annotation type ULIDs (array).
        :type select_annotation_types: List[str]
        :param select_signals: Include metrics/events for these signal ULIDs (array).
        :type select_signals: List[str]
        :param select_system_elements: Include metrics/events for all signals belonging to these system elements (array).
        :type select_system_elements: List[str]
        :param sort: Sort fields (e.g. '-timestamp', 'timestamp').
        :type sort: str
        :param start_time: Filter by start time (ISO format: YYYY-MM-DD HH:MM:SS).
        :type start_time: str
        :param take: The number of items per page (default 10).
        :type take: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_page_metric_serialize(
            end_time=end_time,
            filter_by_annotation_types=filter_by_annotation_types,
            page=page,
            select_all=select_all,
            select_annotation_types=select_annotation_types,
            select_signals=select_signals,
            select_system_elements=select_system_elements,
            sort=sort,
            start_time=start_time,
            take=take,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: dict[str, str | None] = {
            '200': "PaginatedMetric",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '419': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_page_without_preload_content(
        self,
        end_time: Annotated[StrictStr | None, Field(description="Filter by end time (ISO format: YYYY-MM-DD HH:MM:SS).")] = None,
        filter_by_annotation_types: Annotated[list[StrictStr] | None, Field(description="After selection, restrict to metrics/events that are annotated with these annotation types (array of ULIDs).")] = None,
        page: Annotated[StrictInt | None, Field(description="The page number to retrieve (default 1).")] = None,
        select_all: Annotated[StrictBool | None, Field(description="Return all metrics together with annotation-derived events for the filters. When true, 'select_signals' and 'select_annotation_types' must NOT be provided.")] = None,
        select_annotation_types: Annotated[list[StrictStr] | None, Field(description="Include annotation-derived events for these annotation type ULIDs (array).")] = None,
        select_signals: Annotated[list[StrictStr] | None, Field(description="Include metrics/events for these signal ULIDs (array).")] = None,
        select_system_elements: Annotated[list[StrictStr] | None, Field(description="Include metrics/events for all signals belonging to these system elements (array).")] = None,
        sort: Annotated[StrictStr | None, Field(description="Sort fields (e.g. '-timestamp', 'timestamp').")] = None,
        start_time: Annotated[StrictStr | None, Field(description="Filter by start time (ISO format: YYYY-MM-DD HH:MM:SS).")] = None,
        take: Annotated[StrictInt | None, Field(description="The number of items per page (default 10).")] = None,
        _request_timeout: None | Annotated[StrictFloat, Field(gt=0)] | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List time series metrics

        Retrieve paginated ACTUAL HISTORIAN DATA - historicized application signals (sensor readings and logged parameters) mapped to signals.  Selection semantics: - select_signals → metrics for those signals - select_annotation_types → annotation-derived events for those annotation types - select_signals + select_annotation_types → combination of both - select_all → all metrics + all annotation-derived events - filter_by_annotation_types → further restrict to entries annotated with these types

        :param end_time: Filter by end time (ISO format: YYYY-MM-DD HH:MM:SS).
        :type end_time: str
        :param filter_by_annotation_types: After selection, restrict to metrics/events that are annotated with these annotation types (array of ULIDs).
        :type filter_by_annotation_types: List[str]
        :param page: The page number to retrieve (default 1).
        :type page: int
        :param select_all: Return all metrics together with annotation-derived events for the filters. When true, 'select_signals' and 'select_annotation_types' must NOT be provided.
        :type select_all: bool
        :param select_annotation_types: Include annotation-derived events for these annotation type ULIDs (array).
        :type select_annotation_types: List[str]
        :param select_signals: Include metrics/events for these signal ULIDs (array).
        :type select_signals: List[str]
        :param select_system_elements: Include metrics/events for all signals belonging to these system elements (array).
        :type select_system_elements: List[str]
        :param sort: Sort fields (e.g. '-timestamp', 'timestamp').
        :type sort: str
        :param start_time: Filter by start time (ISO format: YYYY-MM-DD HH:MM:SS).
        :type start_time: str
        :param take: The number of items per page (default 10).
        :type take: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_page_metric_serialize(
            end_time=end_time,
            filter_by_annotation_types=filter_by_annotation_types,
            page=page,
            select_all=select_all,
            select_annotation_types=select_annotation_types,
            select_signals=select_signals,
            select_system_elements=select_system_elements,
            sort=sort,
            start_time=start_time,
            take=take,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: dict[str, str | None] = {
            '200': "PaginatedMetric",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '419': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_page_metric_serialize(
        self,
        end_time,
        filter_by_annotation_types,
        page,
        select_all,
        select_annotation_types,
        select_signals,
        select_system_elements,
        sort,
        start_time,
        take,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: dict[str, str] = {
            'filter_by_annotation_types': 'multi',
            'select_annotation_types': 'multi',
            'select_signals': 'multi',
            'select_system_elements': 'multi',
        }

        _path_params: dict[str, str] = {}
        _query_params: list[tuple[str, str]] = []
        _header_params: dict[str, str | None] = _headers or {}
        _form_params: list[tuple[str, str]] = []
        _files: dict[
            str, str | bytes | list[str] | list[bytes] | list[tuple[str, bytes]]
        ] = {}
        _body_params: bytes | None = None

        # process the path parameters
        # process the query parameters
        if end_time is not None:

            _query_params.append(('end_time', end_time))

        if filter_by_annotation_types is not None:

            _query_params.append(('filter_by_annotation_types', filter_by_annotation_types))

        if page is not None:

            _query_params.append(('page', page))

        if select_all is not None:

            _query_params.append(('select_all', select_all))

        if select_annotation_types is not None:

            _query_params.append(('select_annotation_types', select_annotation_types))

        if select_signals is not None:

            _query_params.append(('select_signals', select_signals))

        if select_system_elements is not None:

            _query_params.append(('select_system_elements', select_system_elements))

        if sort is not None:

            _query_params.append(('sort', sort))

        if start_time is not None:

            _query_params.append(('start_time', start_time))

        if take is not None:

            _query_params.append(('take', take))

        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: list[str] = [
            'ApiKeyAuth',
            'OIDC'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v1/historian/metrics/page',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


