"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from typing import Annotated, Any

from pydantic import Field, StrictFloat, StrictInt, StrictStr, validate_call

from prekit_edge_node_api.api_client import ApiClient, RequestSerialized
from prekit_edge_node_api.api_response import ApiResponse
from prekit_edge_node_api.models.simple_system_element_tree import SimpleSystemElementTree
from prekit_edge_node_api.rest import RESTResponseType


class SemanticHierarchyApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_one(
        self,
        depth: Annotated[StrictInt | None, Field(description="Maximum depth of the tree to return. Defaults to 7. Depth is counted from the root system element down to the leaves.")] = None,
        root_system_element_id: Annotated[StrictStr | None, Field(description="Optional ULID of a system element to use as the tree root. When omitted the full tree starting from the edge node's root system element is returned. Only pass this when you need a subtree for a specific machine or subsystem.")] = None,
        _request_timeout: None | Annotated[StrictFloat, Field(gt=0)] | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> SimpleSystemElementTree:
        """Get semantic hierarchy of the system with most important information

        Returns a minimal tree of system elements including signals, resources, and annotation types with only id, name, type, and children, as well as information about the edge node that provides connectivity to the system. Output: Recursive tree structure with nodes containing id (ULID), name, type, description, metadata, children, edge_node, and connector_services. Use this to get a semantic overview of the whole system structure and derive connectors, system elements, signals, etc. This endpoint is particularly useful for converting ULIDs to human-readable names: it provides both id and name for all system elements, signals, resources, and annotation types, allowing you to map ULIDs returned by other tools/database queries to their corresponding names for user-facing output.

        :param depth: Maximum depth of the tree to return. Defaults to 7. Depth is counted from the root system element down to the leaves.
        :type depth: int
        :param root_system_element_id: Optional ULID of a system element to use as the tree root. When omitted the full tree starting from the edge node's root system element is returned. Only pass this when you need a subtree for a specific machine or subsystem.
        :type root_system_element_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_one_semantic_hierarchy_serialize(
            depth=depth,
            root_system_element_id=root_system_element_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: dict[str, str | None] = {
            '200': "SimpleSystemElementTree",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '419': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_one_with_http_info(
        self,
        depth: Annotated[StrictInt | None, Field(description="Maximum depth of the tree to return. Defaults to 7. Depth is counted from the root system element down to the leaves.")] = None,
        root_system_element_id: Annotated[StrictStr | None, Field(description="Optional ULID of a system element to use as the tree root. When omitted the full tree starting from the edge node's root system element is returned. Only pass this when you need a subtree for a specific machine or subsystem.")] = None,
        _request_timeout: None | Annotated[StrictFloat, Field(gt=0)] | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[SimpleSystemElementTree]:
        """Get semantic hierarchy of the system with most important information

        Returns a minimal tree of system elements including signals, resources, and annotation types with only id, name, type, and children, as well as information about the edge node that provides connectivity to the system. Output: Recursive tree structure with nodes containing id (ULID), name, type, description, metadata, children, edge_node, and connector_services. Use this to get a semantic overview of the whole system structure and derive connectors, system elements, signals, etc. This endpoint is particularly useful for converting ULIDs to human-readable names: it provides both id and name for all system elements, signals, resources, and annotation types, allowing you to map ULIDs returned by other tools/database queries to their corresponding names for user-facing output.

        :param depth: Maximum depth of the tree to return. Defaults to 7. Depth is counted from the root system element down to the leaves.
        :type depth: int
        :param root_system_element_id: Optional ULID of a system element to use as the tree root. When omitted the full tree starting from the edge node's root system element is returned. Only pass this when you need a subtree for a specific machine or subsystem.
        :type root_system_element_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_one_semantic_hierarchy_serialize(
            depth=depth,
            root_system_element_id=root_system_element_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: dict[str, str | None] = {
            '200': "SimpleSystemElementTree",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '419': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_one_without_preload_content(
        self,
        depth: Annotated[StrictInt | None, Field(description="Maximum depth of the tree to return. Defaults to 7. Depth is counted from the root system element down to the leaves.")] = None,
        root_system_element_id: Annotated[StrictStr | None, Field(description="Optional ULID of a system element to use as the tree root. When omitted the full tree starting from the edge node's root system element is returned. Only pass this when you need a subtree for a specific machine or subsystem.")] = None,
        _request_timeout: None | Annotated[StrictFloat, Field(gt=0)] | tuple[Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get semantic hierarchy of the system with most important information

        Returns a minimal tree of system elements including signals, resources, and annotation types with only id, name, type, and children, as well as information about the edge node that provides connectivity to the system. Output: Recursive tree structure with nodes containing id (ULID), name, type, description, metadata, children, edge_node, and connector_services. Use this to get a semantic overview of the whole system structure and derive connectors, system elements, signals, etc. This endpoint is particularly useful for converting ULIDs to human-readable names: it provides both id and name for all system elements, signals, resources, and annotation types, allowing you to map ULIDs returned by other tools/database queries to their corresponding names for user-facing output.

        :param depth: Maximum depth of the tree to return. Defaults to 7. Depth is counted from the root system element down to the leaves.
        :type depth: int
        :param root_system_element_id: Optional ULID of a system element to use as the tree root. When omitted the full tree starting from the edge node's root system element is returned. Only pass this when you need a subtree for a specific machine or subsystem.
        :type root_system_element_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_one_semantic_hierarchy_serialize(
            depth=depth,
            root_system_element_id=root_system_element_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: dict[str, str | None] = {
            '200': "SimpleSystemElementTree",
            '400': None,
            '401': None,
            '403': None,
            '404': None,
            '419': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_one_semantic_hierarchy_serialize(
        self,
        depth,
        root_system_element_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: dict[str, str] = {
        }

        _path_params: dict[str, str] = {}
        _query_params: list[tuple[str, str]] = []
        _header_params: dict[str, str | None] = _headers or {}
        _form_params: list[tuple[str, str]] = []
        _files: dict[
            str, str | bytes | list[str] | list[bytes] | list[tuple[str, bytes]]
        ] = {}
        _body_params: bytes | None = None

        # process the path parameters
        # process the query parameters
        if depth is not None:

            _query_params.append(('depth', depth))

        if root_system_element_id is not None:

            _query_params.append(('root_system_element_id', root_system_element_id))

        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: list[str] = [
            'ApiKeyAuth',
            'OIDC'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v1/system-elements/simple-tree/',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


