# coding: utf-8

# flake8: noqa

"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.11.1"

# Define package exports
__all__ = [
    "ActivateVirtualSensorApi",
    "AddGrafanaPanelApi",
    "AddGrafanaSignalAsPanelApi",
    "AllowedFileFormatsApi",
    "AnnotateMetricsApi",
    "AnnotationApi",
    "AnnotationOptionApi",
    "AnnotationTypeApi",
    "ApiKeyApi",
    "AppConfigApi",
    "AuthenticationApi",
    "BindDataTagApi",
    "BulkCommissionApi",
    "CleanupVirtualSensorsApi",
    "CommandApi",
    "CompareSignalsApi",
    "ComputationApi",
    "ComputationContextApi",
    "ComputationsBulkAssignApi",
    "CreateAnnotationApi",
    "CreateAnnotationTypeApi",
    "CreateGrafanaDashboardApi",
    "CreateGrafanaFolderApi",
    "CreateSignalApi",
    "CreateSystemElementApi",
    "DataTagApi",
    "DataTagContextApi",
    "DataTagsBulkAssignApi",
    "DeactivateVirtualSensorApi",
    "DeleteGrafanaDashboardApi",
    "DeleteGrafanaFolderApi",
    "DeleteSystemElementApi",
    "DeployVirtualSensorApi",
    "DetectAnomaliesApi",
    "EdgeNodeApi",
    "ExternalRowReferenceApi",
    "ExternalTableRelationshipApi",
    "FigureFromDataApi",
    "FigureFromQueryApi",
    "GenerateShiftReportApi",
    "GetEdgeNodeInfoApi",
    "GetGrafanaDashboardApi",
    "GetGrafanaFolderApi",
    "GetLatestValuesApi",
    "GetObjectMetadataApi",
    "GetServiceDiagnosticsApi",
    "GetSignalDataApi",
    "GetSignalStatisticsApi",
    "GetSkillApi",
    "GetVirtualSensorStatusApi",
    "IsHealthyApi",
    "ListAnnotationTypesApi",
    "ListAvailableDataTagsApi",
    "ListComputationContextsApi",
    "ListComputationsApi",
    "ListDataTagContextsApi",
    "ListGrafanaFoldersApi",
    "ListResourcesApi",
    "ListSkillsApi",
    "LogApi",
    "MCPApi",
    "MetadataApi",
    "MetadataTypeApi",
    "MetricApi",
    "MqttSessionEndRequestApi",
    "MqttSubscriptionsApi",
    "NamespaceGrantApi",
    "NamespaceResourceApi",
    "PatchGrafanaDashboardApi",
    "QueryAnnotationsApi",
    "QueryDatabaseApi",
    "QueryPrometheusMetricsApi",
    "ReadResourceApi",
    "RemoveGrafanaPanelApi",
    "RenderGrafanaDashboardApi",
    "ResetUserPasswordApi",
    "ResolveNamesApi",
    "ResourceApi",
    "ResourceDownloadApi",
    "ResourceReadApi",
    "SaveGrafanaDashboardApi",
    "SearchGrafanaApi",
    "SearchServiceLogsApi",
    "SemanticHierarchyApi",
    "ServiceApi",
    "ServiceHealthApi",
    "ServicesHealthApi",
    "SetObjectMetadataApi",
    "SignalApi",
    "SkillApi",
    "StopDataAcquisitionApi",
    "SystemElementApi",
    "SystemElementTreeApi",
    "UIPluginConfigApi",
    "UpdateDataAcquisitionApi",
    "UpdateGrafanaFolderApi",
    "UpdateSignalApi",
    "UpdateSystemElementApi",
    "UpdateVirtualSensorApi",
    "UserApi",
    "UserNamespacePermissionApi",
    "UserProfileApi",
    "VirtualSensorValidationResultsApi",
    "WebhookAuthZRequestApi",
    "ApiApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ActivateVirtualSensorRequest",
    "ActivateVirtualSensorResponse",
    "AddPanelRequestDoc",
    "AddPanelResponse",
    "AddSignalAsPanelRequest",
    "AllowedFileFormats",
    "AnnotateMetricsRequest",
    "Annotation",
    "AnnotationEntry",
    "AnnotationOption",
    "AnnotationOptionInput",
    "AnnotationSummary",
    "AnnotationType",
    "AnnotationTypeEntry",
    "AnomalyPoint",
    "AnomalySignalSummary",
    "ApiKey",
    "ApiKeyCreateRequest",
    "ApiKeyWithSecret",
    "AppConfig",
    "ArgMapping",
    "ArgMappingInput",
    "AuthOnRegisterRequest",
    "Authentication",
    "BindDataTagRequest",
    "BindDataTagResponse",
    "BindingPlan",
    "BindingResult",
    "BulkCommissionRequest",
    "BulkCommissionResponse",
    "CleanupVirtualSensorsRequest",
    "CleanupVirtualSensorsResourceEntry",
    "CleanupVirtualSensorsResponse",
    "Command",
    "CompareSignalSummary",
    "CompareSignalsRequest",
    "CompareSignalsResponse",
    "Computation",
    "ComputationContext",
    "ComputationContextEntry",
    "ComputationContextNested",
    "ComputationEntry",
    "ComputationRead",
    "ComputationsBulkAssignRequest",
    "ComputationsBulkAssignResponse",
    "ComputationsBulkAssignSkipped",
    "CorrelationPair",
    "CreateAnnotationRequest",
    "CreateAnnotationResponse",
    "CreateAnnotationTypeRequest",
    "CreateAnnotationTypeResponse",
    "CreateDashboardRequestDoc",
    "CreateDashboardResponse",
    "CreateFolderRequest",
    "CreateNamespaceResource",
    "CreateSignalRequest",
    "CreateSignalResponse",
    "CreateSystemElementRequest",
    "CreateSystemElementResponse",
    "CreateUserRequest",
    "DataTag",
    "DataTagContext",
    "DataTagContextEntry",
    "DataTagContextNested",
    "DataTagEntry",
    "DataTagsBulkAssignRequest",
    "DataTagsBulkAssignResponse",
    "DataTagsBulkAssignSkipped",
    "DeactivateVirtualSensorRequest",
    "DeactivateVirtualSensorResponse",
    "DeleteDashboardResponse",
    "DeleteFolderResponse",
    "DeleteSystemElementRequest",
    "DeleteSystemElementResponse",
    "DeployVirtualSensorRequest",
    "DeployVirtualSensorResponse",
    "DetectAnomaliesRequest",
    "DetectAnomaliesResponse",
    "EdgeNode",
    "EdgeNodeSummary",
    "ExternalRowReference",
    "ExternalTableRelationship",
    "FolderResponse",
    "GaugePanel",
    "GetDashboardPanel",
    "GetDashboardResponse",
    "GetDashboardTime",
    "GetEdgeNodeInfoResponse",
    "GetObjectMetadataRequest",
    "GetObjectMetadataResponse",
    "GetServiceDiagnosticsRequest",
    "GetServiceDiagnosticsResponse",
    "GetSkillRequest",
    "GetSkillResponse",
    "GetVirtualSensorStatusRequest",
    "GetVirtualSensorStatusResponse",
    "GrantAccess",
    "GridPos",
    "IsHealthy",
    "Isa95Namespace",
    "KpiDefinition",
    "KpiThresholds",
    "LatestValueEntry",
    "LatestValuesRequest",
    "LatestValuesResponse",
    "ListAnnotationTypesRequest",
    "ListAnnotationTypesResponse",
    "ListComputationContextsRequest",
    "ListComputationContextsResponse",
    "ListComputationEntry",
    "ListComputationsRequest",
    "ListComputationsResponse",
    "ListDataTagContextsRequest",
    "ListDataTagContextsResponse",
    "ListDataTagsRequest",
    "ListDataTagsResponse",
    "ListResourcesRequest",
    "ListResourcesResponse",
    "ListSkillsResponse",
    "ListSkillsResponseEntry",
    "Log",
    "LogEntry",
    "MetaPagination",
    "Metadata",
    "MetadataEntry",
    "MetadataType",
    "Metric",
    "MqttSessionEndRequest",
    "MqttSubscriptions",
    "NameLookupRequest",
    "NameLookupResponse",
    "NameLookupResult",
    "NamespaceResource",
    "PaginatedAnnotation",
    "PaginatedDataTag",
    "PaginatedLog",
    "PaginatedMetric",
    "PaginatedSignal",
    "PaginatedUser",
    "Panel",
    "PasswordResetResponse",
    "PatchDashboardResponse",
    "PatchedAnnotation",
    "PatchedAnnotationOption",
    "PatchedAnnotationType",
    "PatchedApiKeyUpdateRequest",
    "PatchedComputation",
    "PatchedComputationContext",
    "PatchedDataTag",
    "PatchedDataTagContext",
    "PatchedEdgeNode",
    "PatchedExternalTableRelationship",
    "PatchedMetadata",
    "PatchedMetadataType",
    "PatchedPatchDashboardRequest",
    "PatchedPatchUserRequest",
    "PatchedService",
    "PatchedSignalCreate",
    "PatchedSkillWrite",
    "PatchedSystemElementCreate",
    "PatchedUpdateFolderRequest",
    "PatchedUpdateUserProfileRequest",
    "PlotResponse",
    "PlotSpecRequest",
    "PrekitTarget",
    "QueryAnnotationsRequest",
    "QueryAnnotationsResponse",
    "QueryPrometheusRequest",
    "QueryPrometheusResponse",
    "QueryToPlotlyRequest",
    "ReadResourceRequest",
    "ReadResourceResponse",
    "RemovePanelResponse",
    "RenderDashboardRequest",
    "RenderDashboardResponse",
    "Resource",
    "ResourceEntry",
    "ResourceReadResponse",
    "ResourceValidationResult",
    "SafeQueryRequest",
    "SafeQueryResponse",
    "SaveDashboardRequest",
    "SaveDashboardResponse",
    "SearchItem",
    "SearchRequest",
    "SearchServiceLogsRequest",
    "SearchServiceLogsResponse",
    "Service",
    "ServiceDependencies",
    "ServiceDiagnosticEntry",
    "ServiceError",
    "ServiceHealth",
    "ServiceMetrics",
    "ServiceSummary",
    "SetObjectMetadataRequest",
    "SetObjectMetadataResponse",
    "ShiftReportRequest",
    "ShiftReportResponse",
    "ShiftReportSignalKPI",
    "Signal",
    "SignalCreate",
    "SignalDataRequest",
    "SignalDataResponse",
    "SignalDataResult",
    "SignalPlan",
    "SignalResult",
    "SignalStatisticsEntry",
    "SignalStatisticsRequest",
    "SignalStatisticsResponse",
    "SimpleSystemElementTree",
    "Skill",
    "SkillWrite",
    "StatPanel",
    "StopDataAcquisitionRequest",
    "StopDataAcquisitionResponse",
    "SystemElement",
    "SystemElementCreate",
    "SystemElementPlan",
    "SystemElementResult",
    "SystemElementTree",
    "TextPanel",
    "TextPanelOptions",
    "TimeseriesPanel",
    "TreeAnnotationType",
    "TreeNodeData",
    "TreeResource",
    "TreeSignal",
    "TreeSystemElement",
    "UIPluginConfig",
    "UpdateDataAcquisitionRequest",
    "UpdateDataAcquisitionResponse",
    "UpdateSignalRequest",
    "UpdateSignalResponse",
    "UpdateSystemElementRequest",
    "UpdateSystemElementResponse",
    "UpdateUserProfileResponse",
    "UpdateVirtualSensorRequest",
    "UpdateVirtualSensorResponse",
    "User",
    "UserPermissions",
    "UserProfile",
    "ValidationResult",
    "WebhookAuthZRequest",
]

# import apis into sdk package
from prekit_edge_node_api.api.activate_virtual_sensor_api import ActivateVirtualSensorApi as ActivateVirtualSensorApi
from prekit_edge_node_api.api.add_grafana_panel_api import AddGrafanaPanelApi as AddGrafanaPanelApi
from prekit_edge_node_api.api.add_grafana_signal_as_panel_api import AddGrafanaSignalAsPanelApi as AddGrafanaSignalAsPanelApi
from prekit_edge_node_api.api.allowed_file_formats_api import AllowedFileFormatsApi as AllowedFileFormatsApi
from prekit_edge_node_api.api.annotate_metrics_api import AnnotateMetricsApi as AnnotateMetricsApi
from prekit_edge_node_api.api.annotation_api import AnnotationApi as AnnotationApi
from prekit_edge_node_api.api.annotation_option_api import AnnotationOptionApi as AnnotationOptionApi
from prekit_edge_node_api.api.annotation_type_api import AnnotationTypeApi as AnnotationTypeApi
from prekit_edge_node_api.api.api_key_api import ApiKeyApi as ApiKeyApi
from prekit_edge_node_api.api.app_config_api import AppConfigApi as AppConfigApi
from prekit_edge_node_api.api.authentication_api import AuthenticationApi as AuthenticationApi
from prekit_edge_node_api.api.bind_data_tag_api import BindDataTagApi as BindDataTagApi
from prekit_edge_node_api.api.bulk_commission_api import BulkCommissionApi as BulkCommissionApi
from prekit_edge_node_api.api.cleanup_virtual_sensors_api import CleanupVirtualSensorsApi as CleanupVirtualSensorsApi
from prekit_edge_node_api.api.command_api import CommandApi as CommandApi
from prekit_edge_node_api.api.compare_signals_api import CompareSignalsApi as CompareSignalsApi
from prekit_edge_node_api.api.computation_api import ComputationApi as ComputationApi
from prekit_edge_node_api.api.computation_context_api import ComputationContextApi as ComputationContextApi
from prekit_edge_node_api.api.computations_bulk_assign_api import ComputationsBulkAssignApi as ComputationsBulkAssignApi
from prekit_edge_node_api.api.create_annotation_api import CreateAnnotationApi as CreateAnnotationApi
from prekit_edge_node_api.api.create_annotation_type_api import CreateAnnotationTypeApi as CreateAnnotationTypeApi
from prekit_edge_node_api.api.create_grafana_dashboard_api import CreateGrafanaDashboardApi as CreateGrafanaDashboardApi
from prekit_edge_node_api.api.create_grafana_folder_api import CreateGrafanaFolderApi as CreateGrafanaFolderApi
from prekit_edge_node_api.api.create_signal_api import CreateSignalApi as CreateSignalApi
from prekit_edge_node_api.api.create_system_element_api import CreateSystemElementApi as CreateSystemElementApi
from prekit_edge_node_api.api.data_tag_api import DataTagApi as DataTagApi
from prekit_edge_node_api.api.data_tag_context_api import DataTagContextApi as DataTagContextApi
from prekit_edge_node_api.api.data_tags_bulk_assign_api import DataTagsBulkAssignApi as DataTagsBulkAssignApi
from prekit_edge_node_api.api.deactivate_virtual_sensor_api import DeactivateVirtualSensorApi as DeactivateVirtualSensorApi
from prekit_edge_node_api.api.delete_grafana_dashboard_api import DeleteGrafanaDashboardApi as DeleteGrafanaDashboardApi
from prekit_edge_node_api.api.delete_grafana_folder_api import DeleteGrafanaFolderApi as DeleteGrafanaFolderApi
from prekit_edge_node_api.api.delete_system_element_api import DeleteSystemElementApi as DeleteSystemElementApi
from prekit_edge_node_api.api.deploy_virtual_sensor_api import DeployVirtualSensorApi as DeployVirtualSensorApi
from prekit_edge_node_api.api.detect_anomalies_api import DetectAnomaliesApi as DetectAnomaliesApi
from prekit_edge_node_api.api.edge_node_api import EdgeNodeApi as EdgeNodeApi
from prekit_edge_node_api.api.external_row_reference_api import ExternalRowReferenceApi as ExternalRowReferenceApi
from prekit_edge_node_api.api.external_table_relationship_api import ExternalTableRelationshipApi as ExternalTableRelationshipApi
from prekit_edge_node_api.api.figure_from_data_api import FigureFromDataApi as FigureFromDataApi
from prekit_edge_node_api.api.figure_from_query_api import FigureFromQueryApi as FigureFromQueryApi
from prekit_edge_node_api.api.generate_shift_report_api import GenerateShiftReportApi as GenerateShiftReportApi
from prekit_edge_node_api.api.get_edge_node_info_api import GetEdgeNodeInfoApi as GetEdgeNodeInfoApi
from prekit_edge_node_api.api.get_grafana_dashboard_api import GetGrafanaDashboardApi as GetGrafanaDashboardApi
from prekit_edge_node_api.api.get_grafana_folder_api import GetGrafanaFolderApi as GetGrafanaFolderApi
from prekit_edge_node_api.api.get_latest_values_api import GetLatestValuesApi as GetLatestValuesApi
from prekit_edge_node_api.api.get_object_metadata_api import GetObjectMetadataApi as GetObjectMetadataApi
from prekit_edge_node_api.api.get_service_diagnostics_api import GetServiceDiagnosticsApi as GetServiceDiagnosticsApi
from prekit_edge_node_api.api.get_signal_data_api import GetSignalDataApi as GetSignalDataApi
from prekit_edge_node_api.api.get_signal_statistics_api import GetSignalStatisticsApi as GetSignalStatisticsApi
from prekit_edge_node_api.api.get_skill_api import GetSkillApi as GetSkillApi
from prekit_edge_node_api.api.get_virtual_sensor_status_api import GetVirtualSensorStatusApi as GetVirtualSensorStatusApi
from prekit_edge_node_api.api.is_healthy_api import IsHealthyApi as IsHealthyApi
from prekit_edge_node_api.api.list_annotation_types_api import ListAnnotationTypesApi as ListAnnotationTypesApi
from prekit_edge_node_api.api.list_available_data_tags_api import ListAvailableDataTagsApi as ListAvailableDataTagsApi
from prekit_edge_node_api.api.list_computation_contexts_api import ListComputationContextsApi as ListComputationContextsApi
from prekit_edge_node_api.api.list_computations_api import ListComputationsApi as ListComputationsApi
from prekit_edge_node_api.api.list_data_tag_contexts_api import ListDataTagContextsApi as ListDataTagContextsApi
from prekit_edge_node_api.api.list_grafana_folders_api import ListGrafanaFoldersApi as ListGrafanaFoldersApi
from prekit_edge_node_api.api.list_resources_api import ListResourcesApi as ListResourcesApi
from prekit_edge_node_api.api.list_skills_api import ListSkillsApi as ListSkillsApi
from prekit_edge_node_api.api.log_api import LogApi as LogApi
from prekit_edge_node_api.api.mcp_api import MCPApi as MCPApi
from prekit_edge_node_api.api.metadata_api import MetadataApi as MetadataApi
from prekit_edge_node_api.api.metadata_type_api import MetadataTypeApi as MetadataTypeApi
from prekit_edge_node_api.api.metric_api import MetricApi as MetricApi
from prekit_edge_node_api.api.mqtt_session_end_request_api import MqttSessionEndRequestApi as MqttSessionEndRequestApi
from prekit_edge_node_api.api.mqtt_subscriptions_api import MqttSubscriptionsApi as MqttSubscriptionsApi
from prekit_edge_node_api.api.namespace_grant_api import NamespaceGrantApi as NamespaceGrantApi
from prekit_edge_node_api.api.namespace_resource_api import NamespaceResourceApi as NamespaceResourceApi
from prekit_edge_node_api.api.patch_grafana_dashboard_api import PatchGrafanaDashboardApi as PatchGrafanaDashboardApi
from prekit_edge_node_api.api.query_annotations_api import QueryAnnotationsApi as QueryAnnotationsApi
from prekit_edge_node_api.api.query_database_api import QueryDatabaseApi as QueryDatabaseApi
from prekit_edge_node_api.api.query_prometheus_metrics_api import QueryPrometheusMetricsApi as QueryPrometheusMetricsApi
from prekit_edge_node_api.api.read_resource_api import ReadResourceApi as ReadResourceApi
from prekit_edge_node_api.api.remove_grafana_panel_api import RemoveGrafanaPanelApi as RemoveGrafanaPanelApi
from prekit_edge_node_api.api.render_grafana_dashboard_api import RenderGrafanaDashboardApi as RenderGrafanaDashboardApi
from prekit_edge_node_api.api.reset_user_password_api import ResetUserPasswordApi as ResetUserPasswordApi
from prekit_edge_node_api.api.resolve_names_api import ResolveNamesApi as ResolveNamesApi
from prekit_edge_node_api.api.resource_api import ResourceApi as ResourceApi
from prekit_edge_node_api.api.resource_download_api import ResourceDownloadApi as ResourceDownloadApi
from prekit_edge_node_api.api.resource_read_api import ResourceReadApi as ResourceReadApi
from prekit_edge_node_api.api.save_grafana_dashboard_api import SaveGrafanaDashboardApi as SaveGrafanaDashboardApi
from prekit_edge_node_api.api.search_grafana_api import SearchGrafanaApi as SearchGrafanaApi
from prekit_edge_node_api.api.search_service_logs_api import SearchServiceLogsApi as SearchServiceLogsApi
from prekit_edge_node_api.api.semantic_hierarchy_api import SemanticHierarchyApi as SemanticHierarchyApi
from prekit_edge_node_api.api.service_api import ServiceApi as ServiceApi
from prekit_edge_node_api.api.service_health_api import ServiceHealthApi as ServiceHealthApi
from prekit_edge_node_api.api.services_health_api import ServicesHealthApi as ServicesHealthApi
from prekit_edge_node_api.api.set_object_metadata_api import SetObjectMetadataApi as SetObjectMetadataApi
from prekit_edge_node_api.api.signal_api import SignalApi as SignalApi
from prekit_edge_node_api.api.skill_api import SkillApi as SkillApi
from prekit_edge_node_api.api.stop_data_acquisition_api import StopDataAcquisitionApi as StopDataAcquisitionApi
from prekit_edge_node_api.api.system_element_api import SystemElementApi as SystemElementApi
from prekit_edge_node_api.api.system_element_tree_api import SystemElementTreeApi as SystemElementTreeApi
from prekit_edge_node_api.api.ui_plugin_config_api import UIPluginConfigApi as UIPluginConfigApi
from prekit_edge_node_api.api.update_data_acquisition_api import UpdateDataAcquisitionApi as UpdateDataAcquisitionApi
from prekit_edge_node_api.api.update_grafana_folder_api import UpdateGrafanaFolderApi as UpdateGrafanaFolderApi
from prekit_edge_node_api.api.update_signal_api import UpdateSignalApi as UpdateSignalApi
from prekit_edge_node_api.api.update_system_element_api import UpdateSystemElementApi as UpdateSystemElementApi
from prekit_edge_node_api.api.update_virtual_sensor_api import UpdateVirtualSensorApi as UpdateVirtualSensorApi
from prekit_edge_node_api.api.user_api import UserApi as UserApi
from prekit_edge_node_api.api.user_namespace_permission_api import UserNamespacePermissionApi as UserNamespacePermissionApi
from prekit_edge_node_api.api.user_profile_api import UserProfileApi as UserProfileApi
from prekit_edge_node_api.api.virtual_sensor_validation_results_api import VirtualSensorValidationResultsApi as VirtualSensorValidationResultsApi
from prekit_edge_node_api.api.webhook_auth_z_request_api import WebhookAuthZRequestApi as WebhookAuthZRequestApi
from prekit_edge_node_api.api.api_api import ApiApi as ApiApi

# import ApiClient
from prekit_edge_node_api.api_response import ApiResponse as ApiResponse
from prekit_edge_node_api.api_client import ApiClient as ApiClient
from prekit_edge_node_api.configuration import Configuration as Configuration
from prekit_edge_node_api.exceptions import OpenApiException as OpenApiException
from prekit_edge_node_api.exceptions import ApiTypeError as ApiTypeError
from prekit_edge_node_api.exceptions import ApiValueError as ApiValueError
from prekit_edge_node_api.exceptions import ApiKeyError as ApiKeyError
from prekit_edge_node_api.exceptions import ApiAttributeError as ApiAttributeError
from prekit_edge_node_api.exceptions import ApiException as ApiException

# import models into sdk package
from prekit_edge_node_api.models.activate_virtual_sensor_request import ActivateVirtualSensorRequest as ActivateVirtualSensorRequest
from prekit_edge_node_api.models.activate_virtual_sensor_response import ActivateVirtualSensorResponse as ActivateVirtualSensorResponse
from prekit_edge_node_api.models.add_panel_request_doc import AddPanelRequestDoc as AddPanelRequestDoc
from prekit_edge_node_api.models.add_panel_response import AddPanelResponse as AddPanelResponse
from prekit_edge_node_api.models.add_signal_as_panel_request import AddSignalAsPanelRequest as AddSignalAsPanelRequest
from prekit_edge_node_api.models.allowed_file_formats import AllowedFileFormats as AllowedFileFormats
from prekit_edge_node_api.models.annotate_metrics_request import AnnotateMetricsRequest as AnnotateMetricsRequest
from prekit_edge_node_api.models.annotation import Annotation as Annotation
from prekit_edge_node_api.models.annotation_entry import AnnotationEntry as AnnotationEntry
from prekit_edge_node_api.models.annotation_option import AnnotationOption as AnnotationOption
from prekit_edge_node_api.models.annotation_option_input import AnnotationOptionInput as AnnotationOptionInput
from prekit_edge_node_api.models.annotation_summary import AnnotationSummary as AnnotationSummary
from prekit_edge_node_api.models.annotation_type import AnnotationType as AnnotationType
from prekit_edge_node_api.models.annotation_type_entry import AnnotationTypeEntry as AnnotationTypeEntry
from prekit_edge_node_api.models.anomaly_point import AnomalyPoint as AnomalyPoint
from prekit_edge_node_api.models.anomaly_signal_summary import AnomalySignalSummary as AnomalySignalSummary
from prekit_edge_node_api.models.api_key import ApiKey as ApiKey
from prekit_edge_node_api.models.api_key_create_request import ApiKeyCreateRequest as ApiKeyCreateRequest
from prekit_edge_node_api.models.api_key_with_secret import ApiKeyWithSecret as ApiKeyWithSecret
from prekit_edge_node_api.models.app_config import AppConfig as AppConfig
from prekit_edge_node_api.models.arg_mapping import ArgMapping as ArgMapping
from prekit_edge_node_api.models.arg_mapping_input import ArgMappingInput as ArgMappingInput
from prekit_edge_node_api.models.auth_on_register_request import AuthOnRegisterRequest as AuthOnRegisterRequest
from prekit_edge_node_api.models.authentication import Authentication as Authentication
from prekit_edge_node_api.models.bind_data_tag_request import BindDataTagRequest as BindDataTagRequest
from prekit_edge_node_api.models.bind_data_tag_response import BindDataTagResponse as BindDataTagResponse
from prekit_edge_node_api.models.binding_plan import BindingPlan as BindingPlan
from prekit_edge_node_api.models.binding_result import BindingResult as BindingResult
from prekit_edge_node_api.models.bulk_commission_request import BulkCommissionRequest as BulkCommissionRequest
from prekit_edge_node_api.models.bulk_commission_response import BulkCommissionResponse as BulkCommissionResponse
from prekit_edge_node_api.models.cleanup_virtual_sensors_request import CleanupVirtualSensorsRequest as CleanupVirtualSensorsRequest
from prekit_edge_node_api.models.cleanup_virtual_sensors_resource_entry import CleanupVirtualSensorsResourceEntry as CleanupVirtualSensorsResourceEntry
from prekit_edge_node_api.models.cleanup_virtual_sensors_response import CleanupVirtualSensorsResponse as CleanupVirtualSensorsResponse
from prekit_edge_node_api.models.command import Command as Command
from prekit_edge_node_api.models.compare_signal_summary import CompareSignalSummary as CompareSignalSummary
from prekit_edge_node_api.models.compare_signals_request import CompareSignalsRequest as CompareSignalsRequest
from prekit_edge_node_api.models.compare_signals_response import CompareSignalsResponse as CompareSignalsResponse
from prekit_edge_node_api.models.computation import Computation as Computation
from prekit_edge_node_api.models.computation_context import ComputationContext as ComputationContext
from prekit_edge_node_api.models.computation_context_entry import ComputationContextEntry as ComputationContextEntry
from prekit_edge_node_api.models.computation_context_nested import ComputationContextNested as ComputationContextNested
from prekit_edge_node_api.models.computation_entry import ComputationEntry as ComputationEntry
from prekit_edge_node_api.models.computation_read import ComputationRead as ComputationRead
from prekit_edge_node_api.models.computations_bulk_assign_request import ComputationsBulkAssignRequest as ComputationsBulkAssignRequest
from prekit_edge_node_api.models.computations_bulk_assign_response import ComputationsBulkAssignResponse as ComputationsBulkAssignResponse
from prekit_edge_node_api.models.computations_bulk_assign_skipped import ComputationsBulkAssignSkipped as ComputationsBulkAssignSkipped
from prekit_edge_node_api.models.correlation_pair import CorrelationPair as CorrelationPair
from prekit_edge_node_api.models.create_annotation_request import CreateAnnotationRequest as CreateAnnotationRequest
from prekit_edge_node_api.models.create_annotation_response import CreateAnnotationResponse as CreateAnnotationResponse
from prekit_edge_node_api.models.create_annotation_type_request import CreateAnnotationTypeRequest as CreateAnnotationTypeRequest
from prekit_edge_node_api.models.create_annotation_type_response import CreateAnnotationTypeResponse as CreateAnnotationTypeResponse
from prekit_edge_node_api.models.create_dashboard_request_doc import CreateDashboardRequestDoc as CreateDashboardRequestDoc
from prekit_edge_node_api.models.create_dashboard_response import CreateDashboardResponse as CreateDashboardResponse
from prekit_edge_node_api.models.create_folder_request import CreateFolderRequest as CreateFolderRequest
from prekit_edge_node_api.models.create_namespace_resource import CreateNamespaceResource as CreateNamespaceResource
from prekit_edge_node_api.models.create_signal_request import CreateSignalRequest as CreateSignalRequest
from prekit_edge_node_api.models.create_signal_response import CreateSignalResponse as CreateSignalResponse
from prekit_edge_node_api.models.create_system_element_request import CreateSystemElementRequest as CreateSystemElementRequest
from prekit_edge_node_api.models.create_system_element_response import CreateSystemElementResponse as CreateSystemElementResponse
from prekit_edge_node_api.models.create_user_request import CreateUserRequest as CreateUserRequest
from prekit_edge_node_api.models.data_tag import DataTag as DataTag
from prekit_edge_node_api.models.data_tag_context import DataTagContext as DataTagContext
from prekit_edge_node_api.models.data_tag_context_entry import DataTagContextEntry as DataTagContextEntry
from prekit_edge_node_api.models.data_tag_context_nested import DataTagContextNested as DataTagContextNested
from prekit_edge_node_api.models.data_tag_entry import DataTagEntry as DataTagEntry
from prekit_edge_node_api.models.data_tags_bulk_assign_request import DataTagsBulkAssignRequest as DataTagsBulkAssignRequest
from prekit_edge_node_api.models.data_tags_bulk_assign_response import DataTagsBulkAssignResponse as DataTagsBulkAssignResponse
from prekit_edge_node_api.models.data_tags_bulk_assign_skipped import DataTagsBulkAssignSkipped as DataTagsBulkAssignSkipped
from prekit_edge_node_api.models.deactivate_virtual_sensor_request import DeactivateVirtualSensorRequest as DeactivateVirtualSensorRequest
from prekit_edge_node_api.models.deactivate_virtual_sensor_response import DeactivateVirtualSensorResponse as DeactivateVirtualSensorResponse
from prekit_edge_node_api.models.delete_dashboard_response import DeleteDashboardResponse as DeleteDashboardResponse
from prekit_edge_node_api.models.delete_folder_response import DeleteFolderResponse as DeleteFolderResponse
from prekit_edge_node_api.models.delete_system_element_request import DeleteSystemElementRequest as DeleteSystemElementRequest
from prekit_edge_node_api.models.delete_system_element_response import DeleteSystemElementResponse as DeleteSystemElementResponse
from prekit_edge_node_api.models.deploy_virtual_sensor_request import DeployVirtualSensorRequest as DeployVirtualSensorRequest
from prekit_edge_node_api.models.deploy_virtual_sensor_response import DeployVirtualSensorResponse as DeployVirtualSensorResponse
from prekit_edge_node_api.models.detect_anomalies_request import DetectAnomaliesRequest as DetectAnomaliesRequest
from prekit_edge_node_api.models.detect_anomalies_response import DetectAnomaliesResponse as DetectAnomaliesResponse
from prekit_edge_node_api.models.edge_node import EdgeNode as EdgeNode
from prekit_edge_node_api.models.edge_node_summary import EdgeNodeSummary as EdgeNodeSummary
from prekit_edge_node_api.models.external_row_reference import ExternalRowReference as ExternalRowReference
from prekit_edge_node_api.models.external_table_relationship import ExternalTableRelationship as ExternalTableRelationship
from prekit_edge_node_api.models.folder_response import FolderResponse as FolderResponse
from prekit_edge_node_api.models.gauge_panel import GaugePanel as GaugePanel
from prekit_edge_node_api.models.get_dashboard_panel import GetDashboardPanel as GetDashboardPanel
from prekit_edge_node_api.models.get_dashboard_response import GetDashboardResponse as GetDashboardResponse
from prekit_edge_node_api.models.get_dashboard_time import GetDashboardTime as GetDashboardTime
from prekit_edge_node_api.models.get_edge_node_info_response import GetEdgeNodeInfoResponse as GetEdgeNodeInfoResponse
from prekit_edge_node_api.models.get_object_metadata_request import GetObjectMetadataRequest as GetObjectMetadataRequest
from prekit_edge_node_api.models.get_object_metadata_response import GetObjectMetadataResponse as GetObjectMetadataResponse
from prekit_edge_node_api.models.get_service_diagnostics_request import GetServiceDiagnosticsRequest as GetServiceDiagnosticsRequest
from prekit_edge_node_api.models.get_service_diagnostics_response import GetServiceDiagnosticsResponse as GetServiceDiagnosticsResponse
from prekit_edge_node_api.models.get_skill_request import GetSkillRequest as GetSkillRequest
from prekit_edge_node_api.models.get_skill_response import GetSkillResponse as GetSkillResponse
from prekit_edge_node_api.models.get_virtual_sensor_status_request import GetVirtualSensorStatusRequest as GetVirtualSensorStatusRequest
from prekit_edge_node_api.models.get_virtual_sensor_status_response import GetVirtualSensorStatusResponse as GetVirtualSensorStatusResponse
from prekit_edge_node_api.models.grant_access import GrantAccess as GrantAccess
from prekit_edge_node_api.models.grid_pos import GridPos as GridPos
from prekit_edge_node_api.models.is_healthy import IsHealthy as IsHealthy
from prekit_edge_node_api.models.isa95_namespace import Isa95Namespace as Isa95Namespace
from prekit_edge_node_api.models.kpi_definition import KpiDefinition as KpiDefinition
from prekit_edge_node_api.models.kpi_thresholds import KpiThresholds as KpiThresholds
from prekit_edge_node_api.models.latest_value_entry import LatestValueEntry as LatestValueEntry
from prekit_edge_node_api.models.latest_values_request import LatestValuesRequest as LatestValuesRequest
from prekit_edge_node_api.models.latest_values_response import LatestValuesResponse as LatestValuesResponse
from prekit_edge_node_api.models.list_annotation_types_request import ListAnnotationTypesRequest as ListAnnotationTypesRequest
from prekit_edge_node_api.models.list_annotation_types_response import ListAnnotationTypesResponse as ListAnnotationTypesResponse
from prekit_edge_node_api.models.list_computation_contexts_request import ListComputationContextsRequest as ListComputationContextsRequest
from prekit_edge_node_api.models.list_computation_contexts_response import ListComputationContextsResponse as ListComputationContextsResponse
from prekit_edge_node_api.models.list_computation_entry import ListComputationEntry as ListComputationEntry
from prekit_edge_node_api.models.list_computations_request import ListComputationsRequest as ListComputationsRequest
from prekit_edge_node_api.models.list_computations_response import ListComputationsResponse as ListComputationsResponse
from prekit_edge_node_api.models.list_data_tag_contexts_request import ListDataTagContextsRequest as ListDataTagContextsRequest
from prekit_edge_node_api.models.list_data_tag_contexts_response import ListDataTagContextsResponse as ListDataTagContextsResponse
from prekit_edge_node_api.models.list_data_tags_request import ListDataTagsRequest as ListDataTagsRequest
from prekit_edge_node_api.models.list_data_tags_response import ListDataTagsResponse as ListDataTagsResponse
from prekit_edge_node_api.models.list_resources_request import ListResourcesRequest as ListResourcesRequest
from prekit_edge_node_api.models.list_resources_response import ListResourcesResponse as ListResourcesResponse
from prekit_edge_node_api.models.list_skills_response import ListSkillsResponse as ListSkillsResponse
from prekit_edge_node_api.models.list_skills_response_entry import ListSkillsResponseEntry as ListSkillsResponseEntry
from prekit_edge_node_api.models.log import Log as Log
from prekit_edge_node_api.models.log_entry import LogEntry as LogEntry
from prekit_edge_node_api.models.meta_pagination import MetaPagination as MetaPagination
from prekit_edge_node_api.models.metadata import Metadata as Metadata
from prekit_edge_node_api.models.metadata_entry import MetadataEntry as MetadataEntry
from prekit_edge_node_api.models.metadata_type import MetadataType as MetadataType
from prekit_edge_node_api.models.metric import Metric as Metric
from prekit_edge_node_api.models.mqtt_session_end_request import MqttSessionEndRequest as MqttSessionEndRequest
from prekit_edge_node_api.models.mqtt_subscriptions import MqttSubscriptions as MqttSubscriptions
from prekit_edge_node_api.models.name_lookup_request import NameLookupRequest as NameLookupRequest
from prekit_edge_node_api.models.name_lookup_response import NameLookupResponse as NameLookupResponse
from prekit_edge_node_api.models.name_lookup_result import NameLookupResult as NameLookupResult
from prekit_edge_node_api.models.namespace_resource import NamespaceResource as NamespaceResource
from prekit_edge_node_api.models.paginated_annotation import PaginatedAnnotation as PaginatedAnnotation
from prekit_edge_node_api.models.paginated_data_tag import PaginatedDataTag as PaginatedDataTag
from prekit_edge_node_api.models.paginated_log import PaginatedLog as PaginatedLog
from prekit_edge_node_api.models.paginated_metric import PaginatedMetric as PaginatedMetric
from prekit_edge_node_api.models.paginated_signal import PaginatedSignal as PaginatedSignal
from prekit_edge_node_api.models.paginated_user import PaginatedUser as PaginatedUser
from prekit_edge_node_api.models.panel import Panel as Panel
from prekit_edge_node_api.models.password_reset_response import PasswordResetResponse as PasswordResetResponse
from prekit_edge_node_api.models.patch_dashboard_response import PatchDashboardResponse as PatchDashboardResponse
from prekit_edge_node_api.models.patched_annotation import PatchedAnnotation as PatchedAnnotation
from prekit_edge_node_api.models.patched_annotation_option import PatchedAnnotationOption as PatchedAnnotationOption
from prekit_edge_node_api.models.patched_annotation_type import PatchedAnnotationType as PatchedAnnotationType
from prekit_edge_node_api.models.patched_api_key_update_request import PatchedApiKeyUpdateRequest as PatchedApiKeyUpdateRequest
from prekit_edge_node_api.models.patched_computation import PatchedComputation as PatchedComputation
from prekit_edge_node_api.models.patched_computation_context import PatchedComputationContext as PatchedComputationContext
from prekit_edge_node_api.models.patched_data_tag import PatchedDataTag as PatchedDataTag
from prekit_edge_node_api.models.patched_data_tag_context import PatchedDataTagContext as PatchedDataTagContext
from prekit_edge_node_api.models.patched_edge_node import PatchedEdgeNode as PatchedEdgeNode
from prekit_edge_node_api.models.patched_external_table_relationship import PatchedExternalTableRelationship as PatchedExternalTableRelationship
from prekit_edge_node_api.models.patched_metadata import PatchedMetadata as PatchedMetadata
from prekit_edge_node_api.models.patched_metadata_type import PatchedMetadataType as PatchedMetadataType
from prekit_edge_node_api.models.patched_patch_dashboard_request import PatchedPatchDashboardRequest as PatchedPatchDashboardRequest
from prekit_edge_node_api.models.patched_patch_user_request import PatchedPatchUserRequest as PatchedPatchUserRequest
from prekit_edge_node_api.models.patched_service import PatchedService as PatchedService
from prekit_edge_node_api.models.patched_signal_create import PatchedSignalCreate as PatchedSignalCreate
from prekit_edge_node_api.models.patched_skill_write import PatchedSkillWrite as PatchedSkillWrite
from prekit_edge_node_api.models.patched_system_element_create import PatchedSystemElementCreate as PatchedSystemElementCreate
from prekit_edge_node_api.models.patched_update_folder_request import PatchedUpdateFolderRequest as PatchedUpdateFolderRequest
from prekit_edge_node_api.models.patched_update_user_profile_request import PatchedUpdateUserProfileRequest as PatchedUpdateUserProfileRequest
from prekit_edge_node_api.models.plot_response import PlotResponse as PlotResponse
from prekit_edge_node_api.models.plot_spec_request import PlotSpecRequest as PlotSpecRequest
from prekit_edge_node_api.models.prekit_target import PrekitTarget as PrekitTarget
from prekit_edge_node_api.models.query_annotations_request import QueryAnnotationsRequest as QueryAnnotationsRequest
from prekit_edge_node_api.models.query_annotations_response import QueryAnnotationsResponse as QueryAnnotationsResponse
from prekit_edge_node_api.models.query_prometheus_request import QueryPrometheusRequest as QueryPrometheusRequest
from prekit_edge_node_api.models.query_prometheus_response import QueryPrometheusResponse as QueryPrometheusResponse
from prekit_edge_node_api.models.query_to_plotly_request import QueryToPlotlyRequest as QueryToPlotlyRequest
from prekit_edge_node_api.models.read_resource_request import ReadResourceRequest as ReadResourceRequest
from prekit_edge_node_api.models.read_resource_response import ReadResourceResponse as ReadResourceResponse
from prekit_edge_node_api.models.remove_panel_response import RemovePanelResponse as RemovePanelResponse
from prekit_edge_node_api.models.render_dashboard_request import RenderDashboardRequest as RenderDashboardRequest
from prekit_edge_node_api.models.render_dashboard_response import RenderDashboardResponse as RenderDashboardResponse
from prekit_edge_node_api.models.resource import Resource as Resource
from prekit_edge_node_api.models.resource_entry import ResourceEntry as ResourceEntry
from prekit_edge_node_api.models.resource_read_response import ResourceReadResponse as ResourceReadResponse
from prekit_edge_node_api.models.resource_validation_result import ResourceValidationResult as ResourceValidationResult
from prekit_edge_node_api.models.safe_query_request import SafeQueryRequest as SafeQueryRequest
from prekit_edge_node_api.models.safe_query_response import SafeQueryResponse as SafeQueryResponse
from prekit_edge_node_api.models.save_dashboard_request import SaveDashboardRequest as SaveDashboardRequest
from prekit_edge_node_api.models.save_dashboard_response import SaveDashboardResponse as SaveDashboardResponse
from prekit_edge_node_api.models.search_item import SearchItem as SearchItem
from prekit_edge_node_api.models.search_request import SearchRequest as SearchRequest
from prekit_edge_node_api.models.search_service_logs_request import SearchServiceLogsRequest as SearchServiceLogsRequest
from prekit_edge_node_api.models.search_service_logs_response import SearchServiceLogsResponse as SearchServiceLogsResponse
from prekit_edge_node_api.models.service import Service as Service
from prekit_edge_node_api.models.service_dependencies import ServiceDependencies as ServiceDependencies
from prekit_edge_node_api.models.service_diagnostic_entry import ServiceDiagnosticEntry as ServiceDiagnosticEntry
from prekit_edge_node_api.models.service_error import ServiceError as ServiceError
from prekit_edge_node_api.models.service_health import ServiceHealth as ServiceHealth
from prekit_edge_node_api.models.service_metrics import ServiceMetrics as ServiceMetrics
from prekit_edge_node_api.models.service_summary import ServiceSummary as ServiceSummary
from prekit_edge_node_api.models.set_object_metadata_request import SetObjectMetadataRequest as SetObjectMetadataRequest
from prekit_edge_node_api.models.set_object_metadata_response import SetObjectMetadataResponse as SetObjectMetadataResponse
from prekit_edge_node_api.models.shift_report_request import ShiftReportRequest as ShiftReportRequest
from prekit_edge_node_api.models.shift_report_response import ShiftReportResponse as ShiftReportResponse
from prekit_edge_node_api.models.shift_report_signal_kpi import ShiftReportSignalKPI as ShiftReportSignalKPI
from prekit_edge_node_api.models.signal import Signal as Signal
from prekit_edge_node_api.models.signal_create import SignalCreate as SignalCreate
from prekit_edge_node_api.models.signal_data_request import SignalDataRequest as SignalDataRequest
from prekit_edge_node_api.models.signal_data_response import SignalDataResponse as SignalDataResponse
from prekit_edge_node_api.models.signal_data_result import SignalDataResult as SignalDataResult
from prekit_edge_node_api.models.signal_plan import SignalPlan as SignalPlan
from prekit_edge_node_api.models.signal_result import SignalResult as SignalResult
from prekit_edge_node_api.models.signal_statistics_entry import SignalStatisticsEntry as SignalStatisticsEntry
from prekit_edge_node_api.models.signal_statistics_request import SignalStatisticsRequest as SignalStatisticsRequest
from prekit_edge_node_api.models.signal_statistics_response import SignalStatisticsResponse as SignalStatisticsResponse
from prekit_edge_node_api.models.simple_system_element_tree import SimpleSystemElementTree as SimpleSystemElementTree
from prekit_edge_node_api.models.skill import Skill as Skill
from prekit_edge_node_api.models.skill_write import SkillWrite as SkillWrite
from prekit_edge_node_api.models.stat_panel import StatPanel as StatPanel
from prekit_edge_node_api.models.stop_data_acquisition_request import StopDataAcquisitionRequest as StopDataAcquisitionRequest
from prekit_edge_node_api.models.stop_data_acquisition_response import StopDataAcquisitionResponse as StopDataAcquisitionResponse
from prekit_edge_node_api.models.system_element import SystemElement as SystemElement
from prekit_edge_node_api.models.system_element_create import SystemElementCreate as SystemElementCreate
from prekit_edge_node_api.models.system_element_plan import SystemElementPlan as SystemElementPlan
from prekit_edge_node_api.models.system_element_result import SystemElementResult as SystemElementResult
from prekit_edge_node_api.models.system_element_tree import SystemElementTree as SystemElementTree
from prekit_edge_node_api.models.text_panel import TextPanel as TextPanel
from prekit_edge_node_api.models.text_panel_options import TextPanelOptions as TextPanelOptions
from prekit_edge_node_api.models.timeseries_panel import TimeseriesPanel as TimeseriesPanel
from prekit_edge_node_api.models.tree_annotation_type import TreeAnnotationType as TreeAnnotationType
from prekit_edge_node_api.models.tree_node_data import TreeNodeData as TreeNodeData
from prekit_edge_node_api.models.tree_resource import TreeResource as TreeResource
from prekit_edge_node_api.models.tree_signal import TreeSignal as TreeSignal
from prekit_edge_node_api.models.tree_system_element import TreeSystemElement as TreeSystemElement
from prekit_edge_node_api.models.ui_plugin_config import UIPluginConfig as UIPluginConfig
from prekit_edge_node_api.models.update_data_acquisition_request import UpdateDataAcquisitionRequest as UpdateDataAcquisitionRequest
from prekit_edge_node_api.models.update_data_acquisition_response import UpdateDataAcquisitionResponse as UpdateDataAcquisitionResponse
from prekit_edge_node_api.models.update_signal_request import UpdateSignalRequest as UpdateSignalRequest
from prekit_edge_node_api.models.update_signal_response import UpdateSignalResponse as UpdateSignalResponse
from prekit_edge_node_api.models.update_system_element_request import UpdateSystemElementRequest as UpdateSystemElementRequest
from prekit_edge_node_api.models.update_system_element_response import UpdateSystemElementResponse as UpdateSystemElementResponse
from prekit_edge_node_api.models.update_user_profile_response import UpdateUserProfileResponse as UpdateUserProfileResponse
from prekit_edge_node_api.models.update_virtual_sensor_request import UpdateVirtualSensorRequest as UpdateVirtualSensorRequest
from prekit_edge_node_api.models.update_virtual_sensor_response import UpdateVirtualSensorResponse as UpdateVirtualSensorResponse
from prekit_edge_node_api.models.user import User as User
from prekit_edge_node_api.models.user_permissions import UserPermissions as UserPermissions
from prekit_edge_node_api.models.user_profile import UserProfile as UserProfile
from prekit_edge_node_api.models.validation_result import ValidationResult as ValidationResult
from prekit_edge_node_api.models.webhook_auth_z_request import WebhookAuthZRequest as WebhookAuthZRequest

