
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing_extensions import Self


class AddSignalAsPanelRequest(BaseModel):
    """
    AddSignalAsPanelRequest
    """ # noqa: E501
    dashboard_uid: StrictStr = Field(description="UID of the dashboard to add the panel to")
    signal_ids: list[StrictStr] = Field(description="List of signal IDs (ULIDs) to add to the panel")
    panel_type: StrictStr | None = Field(default='timeseries', description="Type of panel to add: 'timeseries' for line charts over time, 'gauge' for gauge visualization, or 'stat' for single big-number KPI display with sparkline. Defaults to 'timeseries'.  * `timeseries` - timeseries * `gauge` - gauge * `stat` - stat")
    __properties: ClassVar[list[str]] = ["dashboard_uid", "signal_ids", "panel_type"]

    @field_validator('panel_type')
    def panel_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['timeseries', 'gauge', 'stat']):
            raise ValueError("must be one of enum values ('timeseries', 'gauge', 'stat')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of AddSignalAsPanelRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of AddSignalAsPanelRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dashboard_uid": obj.get("dashboard_uid"),
            "signal_ids": obj.get("signal_ids"),
            "panel_type": obj.get("panel_type") if obj.get("panel_type") is not None else 'timeseries'
        })
        return _obj


