
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing_extensions import Self


class AllowedFileFormats(BaseModel):
    """
    AllowedFileFormats
    """ # noqa: E501
    resource_type: StrictStr = Field(description="* `py_data_ops` - PY_DATA_OPS * `protocole_documentation` - PROTOCOLE_DOCUMENTATION * `maintenance_and_operator_documentation` - MAINTENANCE_AND_OPERATOR_DOCUMENTATION * `other` - OTHER")
    file_formats: list[StrictStr]
    content_types: list[StrictStr]
    __properties: ClassVar[list[str]] = ["resource_type", "file_formats", "content_types"]

    @field_validator('resource_type')
    def resource_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['py_data_ops', 'protocole_documentation', 'maintenance_and_operator_documentation', 'other']):
            raise ValueError("must be one of enum values ('py_data_ops', 'protocole_documentation', 'maintenance_and_operator_documentation', 'other')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of AllowedFileFormats from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of AllowedFileFormats from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "resource_type": obj.get("resource_type"),
            "file_formats": obj.get("file_formats"),
            "content_types": obj.get("content_types")
        })
        return _obj


