
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing_extensions import Self


class Annotation(BaseModel):
    """
    Annotation
    """ # noqa: E501
    id: StrictStr | None = None
    annotation_type: StrictStr
    annotation_type_name: StrictStr | None = None
    annotation_type_data_type: StrictStr | None = None
    value: Any | None = None
    time_start: datetime = Field(description="Start time of the annotation (mandatory)")
    time_end: datetime | None = Field(default=None, description="End time of the annotation (optional, creates a segment annotation if provided)")
    signals: list[StrictStr] | None = None
    related_annotations: list[StrictStr] | None = None
    external_row_reference: StrictStr | None = None
    created_by: StrictStr | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None
    __properties: ClassVar[list[str]] = ["id", "annotation_type", "annotation_type_name", "annotation_type_data_type", "value", "time_start", "time_end", "signals", "related_annotations", "external_row_reference", "created_by", "created_at", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of Annotation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: set[str] = set([
            "id",
            "annotation_type_name",
            "annotation_type_data_type",
            "created_at",
            "updated_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if value (nullable) is None
        # and model_fields_set contains the field
        if self.value is None and "value" in self.model_fields_set:
            _dict['value'] = None

        # set to None if time_end (nullable) is None
        # and model_fields_set contains the field
        if self.time_end is None and "time_end" in self.model_fields_set:
            _dict['time_end'] = None

        # set to None if external_row_reference (nullable) is None
        # and model_fields_set contains the field
        if self.external_row_reference is None and "external_row_reference" in self.model_fields_set:
            _dict['external_row_reference'] = None

        # set to None if created_by (nullable) is None
        # and model_fields_set contains the field
        if self.created_by is None and "created_by" in self.model_fields_set:
            _dict['created_by'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of Annotation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "annotation_type": obj.get("annotation_type"),
            "annotation_type_name": obj.get("annotation_type_name"),
            "annotation_type_data_type": obj.get("annotation_type_data_type"),
            "value": obj.get("value"),
            "time_start": obj.get("time_start"),
            "time_end": obj.get("time_end"),
            "signals": obj.get("signals"),
            "related_annotations": obj.get("related_annotations"),
            "external_row_reference": obj.get("external_row_reference"),
            "created_by": obj.get("created_by"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


