
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing_extensions import Self

from prekit_edge_node_api.models.anomaly_point import AnomalyPoint


class AnomalySignalSummary(BaseModel):
    """
    AnomalySignalSummary
    """ # noqa: E501
    signal_id: StrictStr
    signal_name: StrictStr
    unit: StrictStr | None
    count: StrictInt
    mean: StrictFloat | StrictInt | None
    stddev: StrictFloat | StrictInt | None
    anomaly_count: StrictInt
    anomaly_rate: StrictFloat | StrictInt | None = Field(description="Fraction of data points flagged as anomalies.")
    top_anomalies: list[AnomalyPoint]
    __properties: ClassVar[list[str]] = ["signal_id", "signal_name", "unit", "count", "mean", "stddev", "anomaly_count", "anomaly_rate", "top_anomalies"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of AnomalySignalSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in top_anomalies (list)
        _items = []
        if self.top_anomalies:
            for _item_top_anomalies in self.top_anomalies:
                if _item_top_anomalies:
                    _items.append(_item_top_anomalies.to_dict())
            _dict['top_anomalies'] = _items
        # set to None if unit (nullable) is None
        # and model_fields_set contains the field
        if self.unit is None and "unit" in self.model_fields_set:
            _dict['unit'] = None

        # set to None if mean (nullable) is None
        # and model_fields_set contains the field
        if self.mean is None and "mean" in self.model_fields_set:
            _dict['mean'] = None

        # set to None if stddev (nullable) is None
        # and model_fields_set contains the field
        if self.stddev is None and "stddev" in self.model_fields_set:
            _dict['stddev'] = None

        # set to None if anomaly_rate (nullable) is None
        # and model_fields_set contains the field
        if self.anomaly_rate is None and "anomaly_rate" in self.model_fields_set:
            _dict['anomaly_rate'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of AnomalySignalSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "signal_id": obj.get("signal_id"),
            "signal_name": obj.get("signal_name"),
            "unit": obj.get("unit"),
            "count": obj.get("count"),
            "mean": obj.get("mean"),
            "stddev": obj.get("stddev"),
            "anomaly_count": obj.get("anomaly_count"),
            "anomaly_rate": obj.get("anomaly_rate"),
            "top_anomalies": [AnomalyPoint.from_dict(_item) for _item in obj["top_anomalies"]] if obj.get("top_anomalies") is not None else None
        })
        return _obj


