
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict
from typing_extensions import Self

from prekit_edge_node_api.models.binding_plan import BindingPlan
from prekit_edge_node_api.models.signal_plan import SignalPlan
from prekit_edge_node_api.models.system_element_plan import SystemElementPlan


class BulkCommissionRequest(BaseModel):
    """
    BulkCommissionRequest
    """ # noqa: E501
    system_elements: list[SystemElementPlan] | None = None
    signals: list[SignalPlan] | None = None
    bindings: list[BindingPlan] | None = None
    __properties: ClassVar[list[str]] = ["system_elements", "signals", "bindings"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of BulkCommissionRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in system_elements (list)
        _items = []
        if self.system_elements:
            for _item_system_elements in self.system_elements:
                if _item_system_elements:
                    _items.append(_item_system_elements.to_dict())
            _dict['system_elements'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in signals (list)
        _items = []
        if self.signals:
            for _item_signals in self.signals:
                if _item_signals:
                    _items.append(_item_signals.to_dict())
            _dict['signals'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in bindings (list)
        _items = []
        if self.bindings:
            for _item_bindings in self.bindings:
                if _item_bindings:
                    _items.append(_item_bindings.to_dict())
            _dict['bindings'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of BulkCommissionRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "system_elements": [SystemElementPlan.from_dict(_item) for _item in obj["system_elements"]] if obj.get("system_elements") is not None else None,
            "signals": [SignalPlan.from_dict(_item) for _item in obj["signals"]] if obj.get("signals") is not None else None,
            "bindings": [BindingPlan.from_dict(_item) for _item in obj["bindings"]] if obj.get("bindings") is not None else None
        })
        return _obj


