
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing_extensions import Self


class ComputationContextEntry(BaseModel):
    """
    ComputationContextEntry
    """ # noqa: E501
    id: StrictStr
    computation_id: StrictStr
    computation_name: StrictStr
    output_signal_id: StrictStr | None
    output_signal_name: StrictStr | None
    arg_mappings: list[dict[str, Any]]
    interval_ms: StrictInt | None
    is_logged: StrictBool
    is_published: StrictBool
    is_ignored: StrictBool
    is_active: StrictBool = Field(description="True if not ignored and has an output signal.")
    __properties: ClassVar[list[str]] = ["id", "computation_id", "computation_name", "output_signal_id", "output_signal_name", "arg_mappings", "interval_ms", "is_logged", "is_published", "is_ignored", "is_active"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of ComputationContextEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if output_signal_id (nullable) is None
        # and model_fields_set contains the field
        if self.output_signal_id is None and "output_signal_id" in self.model_fields_set:
            _dict['output_signal_id'] = None

        # set to None if output_signal_name (nullable) is None
        # and model_fields_set contains the field
        if self.output_signal_name is None and "output_signal_name" in self.model_fields_set:
            _dict['output_signal_name'] = None

        # set to None if interval_ms (nullable) is None
        # and model_fields_set contains the field
        if self.interval_ms is None and "interval_ms" in self.model_fields_set:
            _dict['interval_ms'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of ComputationContextEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "computation_id": obj.get("computation_id"),
            "computation_name": obj.get("computation_name"),
            "output_signal_id": obj.get("output_signal_id"),
            "output_signal_name": obj.get("output_signal_name"),
            "arg_mappings": obj.get("arg_mappings"),
            "interval_ms": obj.get("interval_ms"),
            "is_logged": obj.get("is_logged"),
            "is_published": obj.get("is_published"),
            "is_ignored": obj.get("is_ignored"),
            "is_active": obj.get("is_active")
        })
        return _obj


