
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing_extensions import Self


class CompareSignalSummary(BaseModel):
    """
    CompareSignalSummary
    """ # noqa: E501
    signal_id: StrictStr
    signal_name: StrictStr
    unit: StrictStr | None
    bucket_count: StrictInt
    avg_value: StrictFloat | StrictInt | None
    stddev_value: StrictFloat | StrictInt | None
    __properties: ClassVar[list[str]] = ["signal_id", "signal_name", "unit", "bucket_count", "avg_value", "stddev_value"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of CompareSignalSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if unit (nullable) is None
        # and model_fields_set contains the field
        if self.unit is None and "unit" in self.model_fields_set:
            _dict['unit'] = None

        # set to None if avg_value (nullable) is None
        # and model_fields_set contains the field
        if self.avg_value is None and "avg_value" in self.model_fields_set:
            _dict['avg_value'] = None

        # set to None if stddev_value (nullable) is None
        # and model_fields_set contains the field
        if self.stddev_value is None and "stddev_value" in self.model_fields_set:
            _dict['stddev_value'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of CompareSignalSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "signal_id": obj.get("signal_id"),
            "signal_name": obj.get("signal_name"),
            "unit": obj.get("unit"),
            "bucket_count": obj.get("bucket_count"),
            "avg_value": obj.get("avg_value"),
            "stddev_value": obj.get("stddev_value")
        })
        return _obj


