
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Annotated, Any, ClassVar

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictFloat,
    StrictInt,
    StrictStr,
    field_validator,
)
from typing_extensions import Self


class CreateSignalRequest(BaseModel):
    """
    CreateSignalRequest
    """ # noqa: E501
    name: StrictStr = Field(description="Human-readable signal name (e.g., 'Spindle Temperature', 'Main Pressure', 'Cycle Count').")
    system_element_id: StrictStr = Field(description="ULID of the system element (machine/subsystem) this signal belongs to. Use CreateSystemElement to create one first.")
    data_type: StrictStr = Field(description="Data type of the signal values. Common types: 'float' for analog measurements, 'int' for counters, 'boolean' for status flags, 'string' for text values.  * `int` - INT * `float` - FLOAT * `string` - STRING * `boolean` - BOOLEAN * `datetime` - DATETIME * `int_array` - INT_ARRAY * `float_array` - FLOAT_ARRAY * `string_array` - STRING_ARRAY * `boolean_array` - BOOLEAN_ARRAY * `datetime_array` - DATETIME_ARRAY")
    source: StrictStr | None = Field(default='connector', description="Origin of the signal values. Use 'connector' for hardware-measured signals (default), 'py_data_ops' for computed virtual sensors.  * `connector` - CONNECTOR * `computation` - COMPUTATION * `py_data_ops` - PY_DATA_OPS * `hub` - HUB")
    index_type: StrictStr | None = Field(default='none', description="Indexing type. 'none' for scalar values (default), 'time' for time-series arrays, 'numerical' for indexed arrays.  * `time` - TIME * `numerical` - NUMERICAL * `none` - NONE")
    unit: StrictStr | None = Field(default=None, description="Engineering unit (e.g., '°C', 'bar', 'rpm', 'mm/s', 'kg'). Leave empty if unitless.")
    description: StrictStr | None = Field(default='', description="Description of what this signal measures or represents.")
    min_value: StrictFloat | StrictInt | None = Field(default=None, description="Expected minimum value for range validation and visualization (e.g., 0.0 for pressure).")
    max_value: StrictFloat | StrictInt | None = Field(default=None, description="Expected maximum value for range validation and visualization (e.g., 10.0 for pressure in bar).")
    precision: Annotated[int, Field(le=10, strict=True, ge=0)] | None = Field(default=None, description="Decimal precision for display/storage (e.g., 2 for values like 23.45).")
    data_tag_id: StrictStr | None = Field(default=None, description="ULID of a data tag to bind immediately. When provided, creates a DataTagContext linking the tag to this signal and publishes it to the connector -- data starts flowing within seconds. Equivalent to calling BindDataTag separately, but saves a round trip. Get available tag IDs from ListAvailableDataTags.")
    is_logged: StrictBool | None = Field(default=True, description="Whether to log values to the historian database (default: true). Only used when data_tag_id is provided.")
    is_published: StrictBool | None = Field(default=True, description="Whether to publish values to the MQTT broker (default: true). Only used when data_tag_id is provided.")
    polling_rate_ms: Annotated[int, Field(le=3600000, strict=True, ge=100)] | None = Field(default=None, description="Custom polling interval in milliseconds. Only used when data_tag_id is provided.")
    __properties: ClassVar[list[str]] = ["name", "system_element_id", "data_type", "source", "index_type", "unit", "description", "min_value", "max_value", "precision", "data_tag_id", "is_logged", "is_published", "polling_rate_ms"]

    @field_validator('data_type')
    def data_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['int', 'float', 'string', 'boolean', 'datetime', 'int_array', 'float_array', 'string_array', 'boolean_array', 'datetime_array']):
            raise ValueError("must be one of enum values ('int', 'float', 'string', 'boolean', 'datetime', 'int_array', 'float_array', 'string_array', 'boolean_array', 'datetime_array')")
        return value

    @field_validator('source')
    def source_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['connector', 'computation', 'py_data_ops', 'hub']):
            raise ValueError("must be one of enum values ('connector', 'computation', 'py_data_ops', 'hub')")
        return value

    @field_validator('index_type')
    def index_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['time', 'numerical', 'none']):
            raise ValueError("must be one of enum values ('time', 'numerical', 'none')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of CreateSignalRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if unit (nullable) is None
        # and model_fields_set contains the field
        if self.unit is None and "unit" in self.model_fields_set:
            _dict['unit'] = None

        # set to None if min_value (nullable) is None
        # and model_fields_set contains the field
        if self.min_value is None and "min_value" in self.model_fields_set:
            _dict['min_value'] = None

        # set to None if max_value (nullable) is None
        # and model_fields_set contains the field
        if self.max_value is None and "max_value" in self.model_fields_set:
            _dict['max_value'] = None

        # set to None if precision (nullable) is None
        # and model_fields_set contains the field
        if self.precision is None and "precision" in self.model_fields_set:
            _dict['precision'] = None

        # set to None if polling_rate_ms (nullable) is None
        # and model_fields_set contains the field
        if self.polling_rate_ms is None and "polling_rate_ms" in self.model_fields_set:
            _dict['polling_rate_ms'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of CreateSignalRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "system_element_id": obj.get("system_element_id"),
            "data_type": obj.get("data_type"),
            "source": obj.get("source") if obj.get("source") is not None else 'connector',
            "index_type": obj.get("index_type") if obj.get("index_type") is not None else 'none',
            "unit": obj.get("unit"),
            "description": obj.get("description") if obj.get("description") is not None else '',
            "min_value": obj.get("min_value"),
            "max_value": obj.get("max_value"),
            "precision": obj.get("precision"),
            "data_tag_id": obj.get("data_tag_id"),
            "is_logged": obj.get("is_logged") if obj.get("is_logged") is not None else True,
            "is_published": obj.get("is_published") if obj.get("is_published") is not None else True,
            "polling_rate_ms": obj.get("polling_rate_ms")
        })
        return _obj


