
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Annotated, Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing_extensions import Self

from prekit_edge_node_api.models.panel import Panel


class CreateDashboardRequestDoc(BaseModel):
    """
    DOCS-ONLY serializer used by Spectacular to render the correct OpenAPI schema. Notice 'panels' uses PolymorphicProxySerializer as the child.
    """ # noqa: E501
    title: Annotated[str, Field(strict=True, max_length=255)]
    panels: list[Panel] | None = None
    folder_uid: StrictStr | None = None
    panel_markdown: StrictStr | None = None
    panel_expr: StrictStr | None = Field(default=None, description="Signal ID (ULID) for a simple timeseries panel using the PREKIT datasource in builder mode. Provide a signal ULID (e.g., '01K9W9FBVZCXK76P0GMSW8BG7S').")
    overwrite: StrictBool | None = True
    __properties: ClassVar[list[str]] = ["title", "panels", "folder_uid", "panel_markdown", "panel_expr", "overwrite"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of CreateDashboardRequestDoc from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in panels (list)
        _items = []
        if self.panels:
            for _item_panels in self.panels:
                if _item_panels:
                    _items.append(_item_panels.to_dict())
            _dict['panels'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of CreateDashboardRequestDoc from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "panels": [Panel.from_dict(_item) for _item in obj["panels"]] if obj.get("panels") is not None else None,
            "folder_uid": obj.get("folder_uid"),
            "panel_markdown": obj.get("panel_markdown"),
            "panel_expr": obj.get("panel_expr"),
            "overwrite": obj.get("overwrite") if obj.get("overwrite") is not None else True
        })
        return _obj


