
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing_extensions import Self


class CreateAnnotationRequest(BaseModel):
    """
    CreateAnnotationRequest
    """ # noqa: E501
    annotation_type_id: StrictStr = Field(description="ULID of the annotation type to create an instance of. Get available types from the SemanticHierarchy.")
    value: Any | None = Field(default=None, description="Annotation value. Type depends on the annotation type's data_type: string, integer, float, boolean, datetime (ISO string), or JSON object.")
    time_start: datetime = Field(description="Start time of the annotation (ISO 8601 format).")
    time_end: datetime | None = Field(default=None, description="Optional end time (ISO 8601). Creates a time-range annotation when provided.")
    signal_ids: list[StrictStr] | None = Field(default=None, description="Optional list of signal ULIDs to associate with this annotation.")
    __properties: ClassVar[list[str]] = ["annotation_type_id", "value", "time_start", "time_end", "signal_ids"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of CreateAnnotationRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if value (nullable) is None
        # and model_fields_set contains the field
        if self.value is None and "value" in self.model_fields_set:
            _dict['value'] = None

        # set to None if time_end (nullable) is None
        # and model_fields_set contains the field
        if self.time_end is None and "time_end" in self.model_fields_set:
            _dict['time_end'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of CreateAnnotationRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "annotation_type_id": obj.get("annotation_type_id"),
            "value": obj.get("value"),
            "time_start": obj.get("time_start"),
            "time_end": obj.get("time_end"),
            "signal_ids": obj.get("signal_ids")
        })
        return _obj


