
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing_extensions import Self


class DataTagContextEntry(BaseModel):
    """
    DataTagContextEntry
    """ # noqa: E501
    id: StrictStr
    data_tag_id: StrictStr
    data_tag_name: StrictStr
    data_tag_address: StrictStr | None
    signal_id: StrictStr | None
    signal_name: StrictStr | None
    service_name: StrictStr
    is_logged: StrictBool
    is_published: StrictBool
    is_ignored: StrictBool
    polling_rate_ms: StrictInt | None
    __properties: ClassVar[list[str]] = ["id", "data_tag_id", "data_tag_name", "data_tag_address", "signal_id", "signal_name", "service_name", "is_logged", "is_published", "is_ignored", "polling_rate_ms"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of DataTagContextEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if data_tag_address (nullable) is None
        # and model_fields_set contains the field
        if self.data_tag_address is None and "data_tag_address" in self.model_fields_set:
            _dict['data_tag_address'] = None

        # set to None if signal_id (nullable) is None
        # and model_fields_set contains the field
        if self.signal_id is None and "signal_id" in self.model_fields_set:
            _dict['signal_id'] = None

        # set to None if signal_name (nullable) is None
        # and model_fields_set contains the field
        if self.signal_name is None and "signal_name" in self.model_fields_set:
            _dict['signal_name'] = None

        # set to None if polling_rate_ms (nullable) is None
        # and model_fields_set contains the field
        if self.polling_rate_ms is None and "polling_rate_ms" in self.model_fields_set:
            _dict['polling_rate_ms'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of DataTagContextEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "data_tag_id": obj.get("data_tag_id"),
            "data_tag_name": obj.get("data_tag_name"),
            "data_tag_address": obj.get("data_tag_address"),
            "signal_id": obj.get("signal_id"),
            "signal_name": obj.get("signal_name"),
            "service_name": obj.get("service_name"),
            "is_logged": obj.get("is_logged"),
            "is_published": obj.get("is_published"),
            "is_ignored": obj.get("is_ignored"),
            "polling_rate_ms": obj.get("polling_rate_ms")
        })
        return _obj


