
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing_extensions import Self

from prekit_edge_node_api.models.grid_pos import GridPos
from prekit_edge_node_api.models.prekit_target import PrekitTarget


class GaugePanel(BaseModel):
    """
    GaugePanel
    """ # noqa: E501
    type: StrictStr = Field(description="Use gauge panels to display single KPI values or current status indicators. Uses the PREKIT datasource in builder mode with aggFunc 'last'.  * `gauge` - gauge")
    title: StrictStr
    datasource: dict[str, StrictStr] | None = Field(default=None, description="Do not set — the PREKIT datasource is used by default.")
    grid_pos: GridPos = Field(alias="gridPos")
    targets: list[PrekitTarget]
    __properties: ClassVar[list[str]] = ["type", "title", "datasource", "gridPos", "targets"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['gauge']):
            raise ValueError("must be one of enum values ('gauge')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of GaugePanel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of grid_pos
        if self.grid_pos:
            _dict['gridPos'] = self.grid_pos.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in targets (list)
        _items = []
        if self.targets:
            for _item_targets in self.targets:
                if _item_targets:
                    _items.append(_item_targets.to_dict())
            _dict['targets'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of GaugePanel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "title": obj.get("title"),
            "datasource": obj.get("datasource"),
            "gridPos": GridPos.from_dict(obj["gridPos"]) if obj.get("gridPos") is not None else None,
            "targets": [PrekitTarget.from_dict(_item) for _item in obj["targets"]] if obj.get("targets") is not None else None
        })
        return _obj


