
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing_extensions import Self


class GetEdgeNodeInfoResponse(BaseModel):
    """
    GetEdgeNodeInfoResponse
    """ # noqa: E501
    name: StrictStr
    display_name: StrictStr
    description: StrictStr
    root_system_element_id: StrictStr | None
    root_system_element_name: StrictStr | None
    active_service_count: StrictInt
    total_signal_count: StrictInt
    total_data_tag_count: StrictInt
    __properties: ClassVar[list[str]] = ["name", "display_name", "description", "root_system_element_id", "root_system_element_name", "active_service_count", "total_signal_count", "total_data_tag_count"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of GetEdgeNodeInfoResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if root_system_element_id (nullable) is None
        # and model_fields_set contains the field
        if self.root_system_element_id is None and "root_system_element_id" in self.model_fields_set:
            _dict['root_system_element_id'] = None

        # set to None if root_system_element_name (nullable) is None
        # and model_fields_set contains the field
        if self.root_system_element_name is None and "root_system_element_name" in self.model_fields_set:
            _dict['root_system_element_name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of GetEdgeNodeInfoResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "display_name": obj.get("display_name"),
            "description": obj.get("description"),
            "root_system_element_id": obj.get("root_system_element_id"),
            "root_system_element_name": obj.get("root_system_element_name"),
            "active_service_count": obj.get("active_service_count"),
            "total_signal_count": obj.get("total_signal_count"),
            "total_data_tag_count": obj.get("total_data_tag_count")
        })
        return _obj


