
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Annotated, Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing_extensions import Self


class GetServiceDiagnosticsRequest(BaseModel):
    """
    GetServiceDiagnosticsRequest
    """ # noqa: E501
    service_names: Annotated[list[StrictStr], Field(max_length=20)] | None = Field(default=None, description="List of service names to diagnose. If omitted, diagnoses all services.")
    include_recent_errors: StrictBool | None = Field(default=True, description="Include recent ERROR/CRITICAL logs per service (default true).")
    error_minutes: Annotated[int, Field(le=1440, strict=True, ge=1)] | None = Field(default=30, description="How far back to search for errors in minutes (default 30, max 1440 = 24 hours).")
    __properties: ClassVar[list[str]] = ["service_names", "include_recent_errors", "error_minutes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of GetServiceDiagnosticsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of GetServiceDiagnosticsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "service_names": obj.get("service_names"),
            "include_recent_errors": obj.get("include_recent_errors") if obj.get("include_recent_errors") is not None else True,
            "error_minutes": obj.get("error_minutes") if obj.get("error_minutes") is not None else 30
        })
        return _obj


