
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing_extensions import Self


class LogEntry(BaseModel):
    """
    LogEntry
    """ # noqa: E501
    timestamp: datetime
    level: StrictStr
    message: StrictStr
    logger_name: StrictStr | None
    module_name: StrictStr | None
    function_name: StrictStr | None
    line_no: StrictInt | None
    exc_info: StrictStr | None
    extra: Any | None
    __properties: ClassVar[list[str]] = ["timestamp", "level", "message", "logger_name", "module_name", "function_name", "line_no", "exc_info", "extra"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of LogEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if logger_name (nullable) is None
        # and model_fields_set contains the field
        if self.logger_name is None and "logger_name" in self.model_fields_set:
            _dict['logger_name'] = None

        # set to None if module_name (nullable) is None
        # and model_fields_set contains the field
        if self.module_name is None and "module_name" in self.model_fields_set:
            _dict['module_name'] = None

        # set to None if function_name (nullable) is None
        # and model_fields_set contains the field
        if self.function_name is None and "function_name" in self.model_fields_set:
            _dict['function_name'] = None

        # set to None if line_no (nullable) is None
        # and model_fields_set contains the field
        if self.line_no is None and "line_no" in self.model_fields_set:
            _dict['line_no'] = None

        # set to None if exc_info (nullable) is None
        # and model_fields_set contains the field
        if self.exc_info is None and "exc_info" in self.model_fields_set:
            _dict['exc_info'] = None

        # set to None if extra (nullable) is None
        # and model_fields_set contains the field
        if self.extra is None and "extra" in self.model_fields_set:
            _dict['extra'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of LogEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "timestamp": obj.get("timestamp"),
            "level": obj.get("level"),
            "message": obj.get("message"),
            "logger_name": obj.get("logger_name"),
            "module_name": obj.get("module_name"),
            "function_name": obj.get("function_name"),
            "line_no": obj.get("line_no"),
            "exc_info": obj.get("exc_info"),
            "extra": obj.get("extra")
        })
        return _obj


