
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing_extensions import Self


class Metric(BaseModel):
    """
    Metric
    """ # noqa: E501
    id: StrictInt = Field(description="Unique identifier for the metric record")
    time: datetime = Field(description="Timestamp when the metric was recorded")
    value: StrictStr = Field(description="Metric value (sensor reading or logged parameter)")
    signal_id: StrictStr | None = Field(description="ID of the signal this metric belongs to")
    edge_node_id: StrictStr | None = Field(description="ID of the edge node that recorded this metric")
    from_annotation_id: StrictStr | None = Field(default=None, description="ID of the annotation that generated this metric")
    from_annotation_type_id: StrictStr | None = Field(default=None, description="ID of the annotation type that generated this metric")
    from_annotation_type_name: StrictStr | None = Field(default=None, description="Name of the annotation type that generated this metric")
    __properties: ClassVar[list[str]] = ["id", "time", "value", "signal_id", "edge_node_id", "from_annotation_id", "from_annotation_type_id", "from_annotation_type_name"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of Metric from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if signal_id (nullable) is None
        # and model_fields_set contains the field
        if self.signal_id is None and "signal_id" in self.model_fields_set:
            _dict['signal_id'] = None

        # set to None if edge_node_id (nullable) is None
        # and model_fields_set contains the field
        if self.edge_node_id is None and "edge_node_id" in self.model_fields_set:
            _dict['edge_node_id'] = None

        # set to None if from_annotation_id (nullable) is None
        # and model_fields_set contains the field
        if self.from_annotation_id is None and "from_annotation_id" in self.model_fields_set:
            _dict['from_annotation_id'] = None

        # set to None if from_annotation_type_id (nullable) is None
        # and model_fields_set contains the field
        if self.from_annotation_type_id is None and "from_annotation_type_id" in self.model_fields_set:
            _dict['from_annotation_type_id'] = None

        # set to None if from_annotation_type_name (nullable) is None
        # and model_fields_set contains the field
        if self.from_annotation_type_name is None and "from_annotation_type_name" in self.model_fields_set:
            _dict['from_annotation_type_name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of Metric from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "time": obj.get("time"),
            "value": obj.get("value"),
            "signal_id": obj.get("signal_id"),
            "edge_node_id": obj.get("edge_node_id"),
            "from_annotation_id": obj.get("from_annotation_id"),
            "from_annotation_type_id": obj.get("from_annotation_type_id"),
            "from_annotation_type_name": obj.get("from_annotation_type_name")
        })
        return _obj


