
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Annotated, Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing_extensions import Self

from prekit_edge_node_api.models.computation_context_nested import ComputationContextNested
from prekit_edge_node_api.models.data_tag_context_nested import DataTagContextNested


class PatchedSignalCreate(BaseModel):
    """
    PatchedSignalCreate
    """ # noqa: E501
    id: Annotated[str, Field(strict=True, max_length=26)] | None = Field(default=None, description="ULID of the signal")
    metadata: dict[str, Any] | None = None
    data_tag_contexts: list[DataTagContextNested] | None = None
    computation_contexts: list[ComputationContextNested] | None = None
    name: Annotated[str, Field(strict=True, max_length=255)] | None = Field(default=None, description="Human-readable signal name")
    description: StrictStr | None = None
    source: StrictStr | None = Field(default=None, description="Origin of values (e.g., measured or computed)  * `connector` - Connector * `computation` - Computation * `py_data_ops` - Py Data Ops * `hub` - Hub")
    data_type: StrictStr | None = Field(default=None, description="Metric data type  * `int` - INT * `float` - FLOAT * `string` - STRING * `boolean` - BOOLEAN * `datetime` - DATETIME * `int_array` - INT_ARRAY * `float_array` - FLOAT_ARRAY * `string_array` - STRING_ARRAY * `boolean_array` - BOOLEAN_ARRAY * `datetime_array` - DATETIME_ARRAY * `json` - JSON")
    index_type: StrictStr | None = Field(default=None, description="Indexing (e.g., 'none' for scalar, 'numerical' for vectors or 'time' for timeseries)  * `time` - TIME * `numerical` - NUMERICAL * `none` - NONE")
    unit: Annotated[str, Field(strict=True, max_length=50)] | None = Field(default=None, description="Engineering unit (e.g., °C, bar)")
    precision: Annotated[int, Field(le=9223372036854775807, strict=True, ge=-9223372036854775808)] | None = Field(default=None, description="Decimal precision for display/storage. Negative values round to powers of 10 (e.g., -4 rounds to nearest 10000).")
    min_value: StrictFloat | StrictInt | None = Field(default=None, description="Expected minimum value")
    max_value: StrictFloat | StrictInt | None = Field(default=None, description="Expected maximum value")
    created_at: datetime | None = Field(default=None, description="Creation timestamp")
    updated_at: datetime | None = Field(default=None, description="Last update timestamp")
    normalized_name: StrictStr | None = Field(default=None, description="Internal PascalCase key derived from name", alias="_normalized_name")
    topic_context_section: StrictStr | None = Field(default=None, description="Internal topic context path used to build MQTT topics", alias="_topic_context_section")
    edge_node_id: Annotated[str, Field(strict=True, max_length=255)] | None = Field(default=None, description="Null for local data, source edge node ID for replicated data")
    implements_contract: Annotated[str, Field(strict=True, max_length=100)] | None = Field(default=None, description="Semantic data contract name (e.g., 'EdgeExecutionContext'). Requires data_type='json'.")
    system_element: StrictStr | None = Field(default=None, description="Owning system element (machine/subsystem/assembly/component) providing context")
    __properties: ClassVar[list[str]] = ["id", "metadata", "data_tag_contexts", "computation_contexts", "name", "description", "source", "data_type", "index_type", "unit", "precision", "min_value", "max_value", "created_at", "updated_at", "_normalized_name", "_topic_context_section", "edge_node_id", "implements_contract", "system_element"]

    @field_validator('source')
    def source_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['connector', 'computation', 'py_data_ops', 'hub']):
            raise ValueError("must be one of enum values ('connector', 'computation', 'py_data_ops', 'hub')")
        return value

    @field_validator('data_type')
    def data_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['int', 'float', 'string', 'boolean', 'datetime', 'int_array', 'float_array', 'string_array', 'boolean_array', 'datetime_array', 'json']):
            raise ValueError("must be one of enum values ('int', 'float', 'string', 'boolean', 'datetime', 'int_array', 'float_array', 'string_array', 'boolean_array', 'datetime_array', 'json')")
        return value

    @field_validator('index_type')
    def index_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['time', 'numerical', 'none']):
            raise ValueError("must be one of enum values ('time', 'numerical', 'none')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of PatchedSignalCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: set[str] = set([
            "created_at",
            "updated_at",
            "normalized_name",
            "topic_context_section",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in data_tag_contexts (list)
        _items = []
        if self.data_tag_contexts:
            for _item_data_tag_contexts in self.data_tag_contexts:
                if _item_data_tag_contexts:
                    _items.append(_item_data_tag_contexts.to_dict())
            _dict['data_tag_contexts'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in computation_contexts (list)
        _items = []
        if self.computation_contexts:
            for _item_computation_contexts in self.computation_contexts:
                if _item_computation_contexts:
                    _items.append(_item_computation_contexts.to_dict())
            _dict['computation_contexts'] = _items
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if unit (nullable) is None
        # and model_fields_set contains the field
        if self.unit is None and "unit" in self.model_fields_set:
            _dict['unit'] = None

        # set to None if precision (nullable) is None
        # and model_fields_set contains the field
        if self.precision is None and "precision" in self.model_fields_set:
            _dict['precision'] = None

        # set to None if min_value (nullable) is None
        # and model_fields_set contains the field
        if self.min_value is None and "min_value" in self.model_fields_set:
            _dict['min_value'] = None

        # set to None if max_value (nullable) is None
        # and model_fields_set contains the field
        if self.max_value is None and "max_value" in self.model_fields_set:
            _dict['max_value'] = None

        # set to None if topic_context_section (nullable) is None
        # and model_fields_set contains the field
        if self.topic_context_section is None and "topic_context_section" in self.model_fields_set:
            _dict['_topic_context_section'] = None

        # set to None if edge_node_id (nullable) is None
        # and model_fields_set contains the field
        if self.edge_node_id is None and "edge_node_id" in self.model_fields_set:
            _dict['edge_node_id'] = None

        # set to None if implements_contract (nullable) is None
        # and model_fields_set contains the field
        if self.implements_contract is None and "implements_contract" in self.model_fields_set:
            _dict['implements_contract'] = None

        # set to None if system_element (nullable) is None
        # and model_fields_set contains the field
        if self.system_element is None and "system_element" in self.model_fields_set:
            _dict['system_element'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of PatchedSignalCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "metadata": obj.get("metadata"),
            "data_tag_contexts": [DataTagContextNested.from_dict(_item) for _item in obj["data_tag_contexts"]] if obj.get("data_tag_contexts") is not None else None,
            "computation_contexts": [ComputationContextNested.from_dict(_item) for _item in obj["computation_contexts"]] if obj.get("computation_contexts") is not None else None,
            "name": obj.get("name"),
            "description": obj.get("description"),
            "source": obj.get("source"),
            "data_type": obj.get("data_type"),
            "index_type": obj.get("index_type"),
            "unit": obj.get("unit"),
            "precision": obj.get("precision"),
            "min_value": obj.get("min_value"),
            "max_value": obj.get("max_value"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "_normalized_name": obj.get("_normalized_name"),
            "_topic_context_section": obj.get("_topic_context_section"),
            "edge_node_id": obj.get("edge_node_id"),
            "implements_contract": obj.get("implements_contract"),
            "system_element": obj.get("system_element")
        })
        return _obj


