
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Annotated, Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing_extensions import Self


class QueryAnnotationsRequest(BaseModel):
    """
    QueryAnnotationsRequest
    """ # noqa: E501
    system_element_ids: list[StrictStr] | None = Field(default=None, description="ULIDs of system elements. Auto-expands to include child signals and annotation types.")
    annotation_type_ids: list[StrictStr] | None = Field(default=None, description="ULIDs of specific annotation types to filter by.")
    signal_ids: list[StrictStr] | None = Field(default=None, description="ULIDs of signals to filter annotations by.")
    minutes: Annotated[int, Field(le=43200, strict=True, ge=1)] | None = Field(default=1440, description="Time window in minutes to look back from now (default 1440 = 24h, max 43200 = 30 days).")
    limit: Annotated[int, Field(le=500, strict=True, ge=1)] | None = Field(default=50, description="Maximum number of annotations to return (default 50, max 500).")
    __properties: ClassVar[list[str]] = ["system_element_ids", "annotation_type_ids", "signal_ids", "minutes", "limit"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of QueryAnnotationsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of QueryAnnotationsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "system_element_ids": obj.get("system_element_ids"),
            "annotation_type_ids": obj.get("annotation_type_ids"),
            "signal_ids": obj.get("signal_ids"),
            "minutes": obj.get("minutes") if obj.get("minutes") is not None else 1440,
            "limit": obj.get("limit") if obj.get("limit") is not None else 50
        })
        return _obj


