
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Annotated, Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing_extensions import Self


class QueryPrometheusRequest(BaseModel):
    """
    QueryPrometheusRequest
    """ # noqa: E501
    query: StrictStr = Field(description="PromQL expression to execute (e.g., 'up', 'rate(node_cpu_seconds_total{mode=\"idle\"}[5m])').")
    query_type: StrictStr | None = Field(default='instant', description="Query type: 'instant' for current values, 'range' for time series (default: instant).  * `instant` - instant * `range` - range")
    minutes: Annotated[int, Field(le=1440, strict=True, ge=1)] | None = Field(default=60, description="Lookback window in minutes for range queries (default 60, max 1440 = 24 hours).")
    step_seconds: Annotated[int, Field(le=3600, strict=True, ge=15)] | None = Field(default=60, description="Step interval in seconds for range queries (default 60).")
    __properties: ClassVar[list[str]] = ["query", "query_type", "minutes", "step_seconds"]

    @field_validator('query_type')
    def query_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['instant', 'range']):
            raise ValueError("must be one of enum values ('instant', 'range')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of QueryPrometheusRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of QueryPrometheusRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "query": obj.get("query"),
            "query_type": obj.get("query_type") if obj.get("query_type") is not None else 'instant',
            "minutes": obj.get("minutes") if obj.get("minutes") is not None else 60,
            "step_seconds": obj.get("step_seconds") if obj.get("step_seconds") is not None else 60
        })
        return _obj


