
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing_extensions import Self


class QueryToPlotlyRequest(BaseModel):
    """
    QueryToPlotlyRequest
    """ # noqa: E501
    query: StrictStr = Field(description="Parameterized or literal SELECT statement with LIMIT <= 500")
    type: StrictStr | None = Field(default='scatter', description="Plotly trace type to use for all columns (default: scatter). Options include scatter, bar, line, etc.  * `bar` - bar * `barpolar` - barpolar * `box` - box * `candlestick` - candlestick * `carpet` - carpet * `choropleth` - choropleth * `choroplethmap` - choroplethmap * `choroplethmapbox` - choroplethmapbox * `cone` - cone * `contour` - contour * `contourcarpet` - contourcarpet * `densitymap` - densitymap * `densitymapbox` - densitymapbox * `funnel` - funnel * `funnelarea` - funnelarea * `heatmap` - heatmap * `histogram` - histogram * `histogram2d` - histogram2d * `histogram2dcontour` - histogram2dcontour * `icicle` - icicle * `image` - image * `indicator` - indicator * `isosurface` - isosurface * `mesh3d` - mesh3d * `ohlc` - ohlc * `parcats` - parcats * `parcoords` - parcoords * `pie` - pie * `sankey` - sankey * `scatter` - scatter * `scatter3d` - scatter3d * `scattercarpet` - scattercarpet * `scattergeo` - scattergeo * `scattergl` - scattergl * `scattermap` - scattermap * `scattermapbox` - scattermapbox * `scatterpolar` - scatterpolar * `scatterpolargl` - scatterpolargl * `scattersmith` - scattersmith * `scatterternary` - scatterternary * `splom` - splom * `streamtube` - streamtube * `sunburst` - sunburst * `surface` - surface * `table` - table * `treemap` - treemap * `violin` - violin * `volume` - volume * `waterfall` - waterfall")
    title: StrictStr | None = Field(default=None, description="Optional plot title. If provided, will be set in the layout.title.text property of the resulting Plotly figure.")
    xlabel: StrictStr | None = Field(default=None, description="Optional X-axis label. If provided, will be set in the layout.xaxis.title.text property of the resulting Plotly figure.")
    ylabel: StrictStr | None = Field(default=None, description="Optional Y-axis label. If provided, will be set in the layout.yaxis.title.text property of the resulting Plotly figure.")
    output_format: StrictStr | None = Field(default='json', description="Output format: 'json' returns the Plotly figure JSON (default), 'png' returns a base64-encoded PNG image.  * `json` - json * `png` - png")
    __properties: ClassVar[list[str]] = ["query", "type", "title", "xlabel", "ylabel", "output_format"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['bar', 'barpolar', 'box', 'candlestick', 'carpet', 'choropleth', 'choroplethmap', 'choroplethmapbox', 'cone', 'contour', 'contourcarpet', 'densitymap', 'densitymapbox', 'funnel', 'funnelarea', 'heatmap', 'histogram', 'histogram2d', 'histogram2dcontour', 'icicle', 'image', 'indicator', 'isosurface', 'mesh3d', 'ohlc', 'parcats', 'parcoords', 'pie', 'sankey', 'scatter', 'scatter3d', 'scattercarpet', 'scattergeo', 'scattergl', 'scattermap', 'scattermapbox', 'scatterpolar', 'scatterpolargl', 'scattersmith', 'scatterternary', 'splom', 'streamtube', 'sunburst', 'surface', 'table', 'treemap', 'violin', 'volume', 'waterfall']):
            raise ValueError("must be one of enum values ('bar', 'barpolar', 'box', 'candlestick', 'carpet', 'choropleth', 'choroplethmap', 'choroplethmapbox', 'cone', 'contour', 'contourcarpet', 'densitymap', 'densitymapbox', 'funnel', 'funnelarea', 'heatmap', 'histogram', 'histogram2d', 'histogram2dcontour', 'icicle', 'image', 'indicator', 'isosurface', 'mesh3d', 'ohlc', 'parcats', 'parcoords', 'pie', 'sankey', 'scatter', 'scatter3d', 'scattercarpet', 'scattergeo', 'scattergl', 'scattermap', 'scattermapbox', 'scatterpolar', 'scatterpolargl', 'scattersmith', 'scatterternary', 'splom', 'streamtube', 'sunburst', 'surface', 'table', 'treemap', 'violin', 'volume', 'waterfall')")
        return value

    @field_validator('output_format')
    def output_format_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['json', 'png']):
            raise ValueError("must be one of enum values ('json', 'png')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of QueryToPlotlyRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        # set to None if xlabel (nullable) is None
        # and model_fields_set contains the field
        if self.xlabel is None and "xlabel" in self.model_fields_set:
            _dict['xlabel'] = None

        # set to None if ylabel (nullable) is None
        # and model_fields_set contains the field
        if self.ylabel is None and "ylabel" in self.model_fields_set:
            _dict['ylabel'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of QueryToPlotlyRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "query": obj.get("query"),
            "type": obj.get("type") if obj.get("type") is not None else 'scatter',
            "title": obj.get("title"),
            "xlabel": obj.get("xlabel"),
            "ylabel": obj.get("ylabel"),
            "output_format": obj.get("output_format") if obj.get("output_format") is not None else 'json'
        })
        return _obj


