
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing_extensions import Self


class ResourceEntry(BaseModel):
    """
    ResourceEntry
    """ # noqa: E501
    id: StrictStr
    display_name: StrictStr | None
    filename: StrictStr
    fileformat: StrictStr
    resource_type: StrictStr
    description: StrictStr | None
    system_element_id: StrictStr | None
    system_element_name: StrictStr | None
    validation_status: StrictStr | None
    validation_error: StrictStr | None
    size_bytes: StrictInt | None
    is_text: StrictBool = Field(description="True if the file content can be read as text.")
    created_at: datetime
    updated_at: datetime
    __properties: ClassVar[list[str]] = ["id", "display_name", "filename", "fileformat", "resource_type", "description", "system_element_id", "system_element_name", "validation_status", "validation_error", "size_bytes", "is_text", "created_at", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of ResourceEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if display_name (nullable) is None
        # and model_fields_set contains the field
        if self.display_name is None and "display_name" in self.model_fields_set:
            _dict['display_name'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if system_element_id (nullable) is None
        # and model_fields_set contains the field
        if self.system_element_id is None and "system_element_id" in self.model_fields_set:
            _dict['system_element_id'] = None

        # set to None if system_element_name (nullable) is None
        # and model_fields_set contains the field
        if self.system_element_name is None and "system_element_name" in self.model_fields_set:
            _dict['system_element_name'] = None

        # set to None if validation_status (nullable) is None
        # and model_fields_set contains the field
        if self.validation_status is None and "validation_status" in self.model_fields_set:
            _dict['validation_status'] = None

        # set to None if validation_error (nullable) is None
        # and model_fields_set contains the field
        if self.validation_error is None and "validation_error" in self.model_fields_set:
            _dict['validation_error'] = None

        # set to None if size_bytes (nullable) is None
        # and model_fields_set contains the field
        if self.size_bytes is None and "size_bytes" in self.model_fields_set:
            _dict['size_bytes'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of ResourceEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "display_name": obj.get("display_name"),
            "filename": obj.get("filename"),
            "fileformat": obj.get("fileformat"),
            "resource_type": obj.get("resource_type"),
            "description": obj.get("description"),
            "system_element_id": obj.get("system_element_id"),
            "system_element_name": obj.get("system_element_name"),
            "validation_status": obj.get("validation_status"),
            "validation_error": obj.get("validation_error"),
            "size_bytes": obj.get("size_bytes"),
            "is_text": obj.get("is_text"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


