
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing_extensions import Self


class ResourceReadResponse(BaseModel):
    """
    ResourceReadResponse
    """ # noqa: E501
    resource_id: StrictStr = Field(description="Unique identifier of the resource")
    filename: StrictStr = Field(description="Name of the resource file")
    resource_type: StrictStr = Field(description="Type of the resource")
    fileformat: StrictStr = Field(description="File format of the resource")
    content: StrictStr = Field(description="Text content extracted from the resource")
    content_length: StrictInt = Field(description="Length of the content in characters")
    read_at: datetime = Field(description="Timestamp when the content was read")
    __properties: ClassVar[list[str]] = ["resource_id", "filename", "resource_type", "fileformat", "content", "content_length", "read_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of ResourceReadResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of ResourceReadResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "resource_id": obj.get("resource_id"),
            "filename": obj.get("filename"),
            "resource_type": obj.get("resource_type"),
            "fileformat": obj.get("fileformat"),
            "content": obj.get("content"),
            "content_length": obj.get("content_length"),
            "read_at": obj.get("read_at")
        })
        return _obj


