
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Annotated, Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing_extensions import Self


class Resource(BaseModel):
    """
    Resource
    """ # noqa: E501
    id: Annotated[str, Field(strict=True, max_length=26)] | None = Field(default=None, description="ULID of the resource")
    metadata: dict[str, Any] | None = None
    filename: StrictStr | None = None
    fileformat: StrictStr = Field(description="* `.py` - PY * `.pdf` - PDF * `.txt` - TXT * `.json` - JSON * `.xml` - XML * `.yml` - YML * `.csv` - CSV * `.png` - PNG * `.jpg` - JPG * `.bmp` - BMP * `.tiff` - TIFF * `.webp` - WEBP * `.css` - CSS")
    is_related_file_deleted: StrictBool | None = None
    thumbnail: StrictStr | None = None
    path: list[StrictStr] | None = None
    content_type: StrictStr | None = Field(default=None, description="* `text/x-python` - PY * `text/x-python-script` - PY_SCRIPT * `application/pdf` - PDF * `text/plain` - TXT * `application/json` - JSON * `application/xml` - XML * `text/yaml` - YAML * `text/yml` - YML * `text/csv` - CSV * `image/png` - PNG * `image/jpeg` - JPEG * `image/jpg` - JPG * `image/bmp` - BMP * `image/tiff` - TIFF * `image/webp` - WEBP * `text/css` - CSS")
    system_element_name: StrictStr | None = None
    display_name: Annotated[str, Field(strict=True, max_length=255)] | None = Field(default=None, description="Human-readable name for the resource")
    resource_type: StrictStr | None = Field(default='other', description="Type of resource (e.g., py_data_ops for virtual sensors or documentation assets)  * `py_data_ops` - PY_DATA_OPS * `protocole_documentation` - PROTOCOLE_DOCUMENTATION * `maintenance_and_operator_documentation` - MAINTENANCE_AND_OPERATOR_DOCUMENTATION * `other` - OTHER")
    description: StrictStr | None = Field(default=None, description="Optional description of the resource")
    created_at: datetime | None = Field(default=None, description="Creation timestamp")
    updated_at: datetime | None = Field(default=None, description="Last update timestamp")
    is_valid: StrictBool | None = Field(default=True, description="True if the file format matches the resource type")
    size_bytes: Annotated[int, Field(le=9223372036854775807, strict=True, ge=-9223372036854775808)] | None = Field(default=None, description="File size in bytes")
    validation_status: StrictStr | None = Field(default=None, description="Validation status for Python virtual sensor files (pending/valid/invalid)  * `pending` - Pending * `valid` - Valid * `invalid` - Invalid")
    validation_error: StrictStr | None = Field(default=None, description="Error message if validation failed")
    validated_at: datetime | None = Field(default=None, description="Timestamp when validation completed")
    edge_node_id: Annotated[str, Field(strict=True, max_length=255)] | None = Field(default=None, description="Null for local data, source edge node ID for replicated data")
    system_element: StrictStr | None = Field(default=None, description="System element this resource is associated with")
    __properties: ClassVar[list[str]] = ["id", "metadata", "filename", "fileformat", "is_related_file_deleted", "thumbnail", "path", "content_type", "system_element_name", "display_name", "resource_type", "description", "created_at", "updated_at", "is_valid", "size_bytes", "validation_status", "validation_error", "validated_at", "edge_node_id", "system_element"]

    @field_validator('fileformat')
    def fileformat_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['.py', '.pdf', '.txt', '.json', '.xml', '.yml', '.csv', '.png', '.jpg', '.bmp', '.tiff', '.webp', '.css']):
            raise ValueError("must be one of enum values ('.py', '.pdf', '.txt', '.json', '.xml', '.yml', '.csv', '.png', '.jpg', '.bmp', '.tiff', '.webp', '.css')")
        return value

    @field_validator('content_type')
    def content_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['text/x-python', 'text/x-python-script', 'application/pdf', 'text/plain', 'application/json', 'application/xml', 'text/yaml', 'text/yml', 'text/csv', 'image/png', 'image/jpeg', 'image/jpg', 'image/bmp', 'image/tiff', 'image/webp', 'text/css']):
            raise ValueError("must be one of enum values ('text/x-python', 'text/x-python-script', 'application/pdf', 'text/plain', 'application/json', 'application/xml', 'text/yaml', 'text/yml', 'text/csv', 'image/png', 'image/jpeg', 'image/jpg', 'image/bmp', 'image/tiff', 'image/webp', 'text/css')")
        return value

    @field_validator('resource_type')
    def resource_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['py_data_ops', 'protocole_documentation', 'maintenance_and_operator_documentation', 'other']):
            raise ValueError("must be one of enum values ('py_data_ops', 'protocole_documentation', 'maintenance_and_operator_documentation', 'other')")
        return value

    @field_validator('validation_status')
    def validation_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['pending', 'valid', 'invalid', '']):
            raise ValueError("must be one of enum values ('pending', 'valid', 'invalid', '')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of Resource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: set[str] = set([
            "filename",
            "is_related_file_deleted",
            "thumbnail",
            "path",
            "content_type",
            "system_element_name",
            "created_at",
            "updated_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if system_element_name (nullable) is None
        # and model_fields_set contains the field
        if self.system_element_name is None and "system_element_name" in self.model_fields_set:
            _dict['system_element_name'] = None

        # set to None if display_name (nullable) is None
        # and model_fields_set contains the field
        if self.display_name is None and "display_name" in self.model_fields_set:
            _dict['display_name'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if size_bytes (nullable) is None
        # and model_fields_set contains the field
        if self.size_bytes is None and "size_bytes" in self.model_fields_set:
            _dict['size_bytes'] = None

        # set to None if validation_status (nullable) is None
        # and model_fields_set contains the field
        if self.validation_status is None and "validation_status" in self.model_fields_set:
            _dict['validation_status'] = None

        # set to None if validation_error (nullable) is None
        # and model_fields_set contains the field
        if self.validation_error is None and "validation_error" in self.model_fields_set:
            _dict['validation_error'] = None

        # set to None if validated_at (nullable) is None
        # and model_fields_set contains the field
        if self.validated_at is None and "validated_at" in self.model_fields_set:
            _dict['validated_at'] = None

        # set to None if edge_node_id (nullable) is None
        # and model_fields_set contains the field
        if self.edge_node_id is None and "edge_node_id" in self.model_fields_set:
            _dict['edge_node_id'] = None

        # set to None if system_element (nullable) is None
        # and model_fields_set contains the field
        if self.system_element is None and "system_element" in self.model_fields_set:
            _dict['system_element'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of Resource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "metadata": obj.get("metadata"),
            "filename": obj.get("filename"),
            "fileformat": obj.get("fileformat"),
            "is_related_file_deleted": obj.get("is_related_file_deleted"),
            "thumbnail": obj.get("thumbnail"),
            "path": obj.get("path"),
            "content_type": obj.get("content_type"),
            "system_element_name": obj.get("system_element_name"),
            "display_name": obj.get("display_name"),
            "resource_type": obj.get("resource_type") if obj.get("resource_type") is not None else 'other',
            "description": obj.get("description"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "is_valid": obj.get("is_valid") if obj.get("is_valid") is not None else True,
            "size_bytes": obj.get("size_bytes"),
            "validation_status": obj.get("validation_status"),
            "validation_error": obj.get("validation_error"),
            "validated_at": obj.get("validated_at"),
            "edge_node_id": obj.get("edge_node_id"),
            "system_element": obj.get("system_element")
        })
        return _obj


