
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing_extensions import Self


class SaveDashboardRequest(BaseModel):
    """
    SaveDashboardRequest
    """ # noqa: E501
    dashboard: dict[str, Any] = Field(description="Full Grafana dashboard JSON model. This is passed directly to the Grafana API. Key fields: title (string), panels (array), time (object with from/to), refresh (string), tags (array), templating (object for variables), annotations (object). For panels, include type, title, gridPos, targets, fieldConfig, and options as needed. Use GetGrafanaDashboard to read an existing dashboard, modify the JSON, and save it back.")
    folder_uid: StrictStr | None = Field(default=None, description="Target folder UID. If omitted, saves to General folder.")
    overwrite: StrictBool | None = Field(default=True, description="Whether to overwrite an existing dashboard with the same uid or title.")
    __properties: ClassVar[list[str]] = ["dashboard", "folder_uid", "overwrite"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of SaveDashboardRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of SaveDashboardRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dashboard": obj.get("dashboard"),
            "folder_uid": obj.get("folder_uid"),
            "overwrite": obj.get("overwrite") if obj.get("overwrite") is not None else True
        })
        return _obj


