
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing_extensions import Self

from prekit_edge_node_api.models.kpi_definition import KpiDefinition
from prekit_edge_node_api.models.service_dependencies import ServiceDependencies
from prekit_edge_node_api.models.service_error import ServiceError
from prekit_edge_node_api.models.service_metrics import ServiceMetrics


class ServiceDiagnosticEntry(BaseModel):
    """
    ServiceDiagnosticEntry
    """ # noqa: E501
    name: StrictStr
    display_name: StrictStr | None
    service_type: StrictStr
    is_active: StrictBool
    status: StrictStr
    visibility: StrictStr = Field(description="Visibility tier: \"default\" (shown by default), \"detail\" (shown on toggle), \"hidden\" (never shown).")
    metrics: ServiceMetrics | None
    dependencies: ServiceDependencies | None
    hierarchy: list[StrictStr]
    recent_errors: list[ServiceError]
    error_count_in_window: StrictInt
    kpis: list[KpiDefinition] | None = None
    __properties: ClassVar[list[str]] = ["name", "display_name", "service_type", "is_active", "status", "visibility", "metrics", "dependencies", "hierarchy", "recent_errors", "error_count_in_window", "kpis"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of ServiceDiagnosticEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of metrics
        if self.metrics:
            _dict['metrics'] = self.metrics.to_dict()
        # override the default output from pydantic by calling `to_dict()` of dependencies
        if self.dependencies:
            _dict['dependencies'] = self.dependencies.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in recent_errors (list)
        _items = []
        if self.recent_errors:
            for _item_recent_errors in self.recent_errors:
                if _item_recent_errors:
                    _items.append(_item_recent_errors.to_dict())
            _dict['recent_errors'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in kpis (list)
        _items = []
        if self.kpis:
            for _item_kpis in self.kpis:
                if _item_kpis:
                    _items.append(_item_kpis.to_dict())
            _dict['kpis'] = _items
        # set to None if display_name (nullable) is None
        # and model_fields_set contains the field
        if self.display_name is None and "display_name" in self.model_fields_set:
            _dict['display_name'] = None

        # set to None if metrics (nullable) is None
        # and model_fields_set contains the field
        if self.metrics is None and "metrics" in self.model_fields_set:
            _dict['metrics'] = None

        # set to None if dependencies (nullable) is None
        # and model_fields_set contains the field
        if self.dependencies is None and "dependencies" in self.model_fields_set:
            _dict['dependencies'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of ServiceDiagnosticEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "display_name": obj.get("display_name"),
            "service_type": obj.get("service_type"),
            "is_active": obj.get("is_active"),
            "status": obj.get("status"),
            "visibility": obj.get("visibility"),
            "metrics": ServiceMetrics.from_dict(obj["metrics"]) if obj.get("metrics") is not None else None,
            "dependencies": ServiceDependencies.from_dict(obj["dependencies"]) if obj.get("dependencies") is not None else None,
            "hierarchy": obj.get("hierarchy"),
            "recent_errors": [ServiceError.from_dict(_item) for _item in obj["recent_errors"]] if obj.get("recent_errors") is not None else None,
            "error_count_in_window": obj.get("error_count_in_window"),
            "kpis": [KpiDefinition.from_dict(_item) for _item in obj["kpis"]] if obj.get("kpis") is not None else None
        })
        return _obj


