
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing_extensions import Self

from prekit_edge_node_api.models.edge_node_summary import EdgeNodeSummary
from prekit_edge_node_api.models.service_summary import ServiceSummary


class SimpleSystemElementTree(BaseModel):
    """
    SimpleSystemElementTree
    """ # noqa: E501
    id: StrictStr = Field(description="pk of the node in SystemElement, Signal, Resource, or AnnotationType tables, allowing for retrieval of detailed information.")
    name: StrictStr
    description: StrictStr | None = None
    type: StrictStr = Field(description="* `system_element` - SYSTEM_ELEMENT * `signal` - SIGNAL * `resource` - RESOURCE * `annotation_type` - ANNOTATION_TYPE")
    children: list[SimpleSystemElementTree] | None = Field(default=None, description="Nodes beneath this node in the system's semantic hierarchy")
    metadata: dict[str, Any] | None = Field(default=None, description="Contextual metadata as key-value map")
    edge_node: EdgeNodeSummary | None = Field(default=None, description="Edge node that is deployed at this level of hierarchy")
    connector_services: list[ServiceSummary] | None = Field(default=None, description="Connectors to devices and data sources deployed at this level of hierarchy")
    __properties: ClassVar[list[str]] = ["id", "name", "description", "type", "children", "metadata", "edge_node", "connector_services"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['system_element', 'signal', 'resource', 'annotation_type']):
            raise ValueError("must be one of enum values ('system_element', 'signal', 'resource', 'annotation_type')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of SimpleSystemElementTree from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in children (list)
        _items = []
        if self.children:
            for _item_children in self.children:
                if _item_children:
                    _items.append(_item_children.to_dict())
            _dict['children'] = _items
        # override the default output from pydantic by calling `to_dict()` of edge_node
        if self.edge_node:
            _dict['edge_node'] = self.edge_node.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in connector_services (list)
        _items = []
        if self.connector_services:
            for _item_connector_services in self.connector_services:
                if _item_connector_services:
                    _items.append(_item_connector_services.to_dict())
            _dict['connector_services'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of SimpleSystemElementTree from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "type": obj.get("type"),
            "children": [SimpleSystemElementTree.from_dict(_item) for _item in obj["children"]] if obj.get("children") is not None else None,
            "metadata": obj.get("metadata"),
            "edge_node": EdgeNodeSummary.from_dict(obj["edge_node"]) if obj.get("edge_node") is not None else None,
            "connector_services": [ServiceSummary.from_dict(_item) for _item in obj["connector_services"]] if obj.get("connector_services") is not None else None
        })
        return _obj

# TODO: Rewrite to not use raise_errors
SimpleSystemElementTree.model_rebuild(raise_errors=False)

