
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing_extensions import Self


class SystemElementPlan(BaseModel):
    """
    SystemElementPlan
    """ # noqa: E501
    ref: StrictStr = Field(description="Local reference key for cross-referencing within this plan.")
    name: StrictStr = Field(description="Human-readable name (e.g., 'CNC Mill', 'Cooling Subsystem').")
    description: StrictStr | None = Field(default='', description="Short description of the element's role or function.")
    parent_ref: StrictStr | None = Field(default=None, description="Ref of a parent system element defined earlier in this plan. Mutually exclusive with parent_id.")
    parent_id: StrictStr | None = Field(default=None, description="ULID of an existing parent system element. Mutually exclusive with parent_ref.")
    __properties: ClassVar[list[str]] = ["ref", "name", "description", "parent_ref", "parent_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of SystemElementPlan from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of SystemElementPlan from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ref": obj.get("ref"),
            "name": obj.get("name"),
            "description": obj.get("description") if obj.get("description") is not None else '',
            "parent_ref": obj.get("parent_ref"),
            "parent_id": obj.get("parent_id")
        })
        return _obj


