
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Annotated, Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing_extensions import Self


class TreeSystemElement(BaseModel):
    """
    TreeSystemElement
    """ # noqa: E501
    id: Annotated[str, Field(strict=True, max_length=26)] | None = Field(default=None, description="ULID of the system element")
    metadata: dict[str, Any] | None = None
    signals: list[StrictStr] | None = Field(default=None, description="List of signal IDs to associate with this element")
    children: list[StrictStr] | None = Field(default=None, description="List of child system element IDs")
    is_root: StrictBool | None = Field(default=None, description="Whether this element is a root element. Root elements are linked to the edge node instance.")
    key: StrictStr | None = Field(default=None, description="Hierarchical path key for the system element")
    topic: StrictStr | None = Field(default=None, description="MQTT topic for the system element")
    node_type: StrictStr | None = 'system_element'
    name: Annotated[str, Field(strict=True, max_length=255)] = Field(description="Human-readable name of the system element (e.g., machine, subsystem, component)")
    description: StrictStr | None = Field(default=None, description="Short description (e.g., machine type, subsystem function, component purpose)")
    created_at: datetime | None = Field(default=None, description="Creation timestamp")
    updated_at: datetime | None = Field(default=None, description="Last update timestamp")
    normalized_name: StrictStr | None = Field(default=None, description="Internal PascalCase key derived from name", alias="_normalized_name")
    topic_context_section: StrictStr | None = Field(default=None, description="Internal topic context path used to build MQTT topics", alias="_topic_context_section")
    edge_node_id: Annotated[str, Field(strict=True, max_length=255)] | None = Field(default=None, description="Null for local data, source edge node ID for replicated data")
    hub_node_id: Annotated[str, Field(strict=True, max_length=255)] | None = Field(default=None, description="Hub EdgeNode ID that owns this element in its unified namespace. Set on hub-local elements and replicated elements accepted into the hub namespace.")
    external_asset_id: Annotated[int, Field(le=9223372036854775807, strict=True, ge=-9223372036854775808)] | None = Field(default=None, description="ID of this asset in an external system (e.g., CMMS, ERP equipment table)")
    lft: StrictInt | None = None
    rght: StrictInt | None = None
    tree_id: StrictInt | None = None
    level: StrictInt | None = None
    parent: StrictStr | None = Field(default=None, description="Parent system element in the hierarchy")
    __properties: ClassVar[list[str]] = ["id", "metadata", "signals", "children", "is_root", "key", "topic", "node_type", "name", "description", "created_at", "updated_at", "_normalized_name", "_topic_context_section", "edge_node_id", "hub_node_id", "external_asset_id", "lft", "rght", "tree_id", "level", "parent"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of TreeSystemElement from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: set[str] = set([
            "signals",
            "children",
            "is_root",
            "key",
            "topic",
            "node_type",
            "created_at",
            "updated_at",
            "normalized_name",
            "topic_context_section",
            "lft",
            "rght",
            "tree_id",
            "level",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if edge_node_id (nullable) is None
        # and model_fields_set contains the field
        if self.edge_node_id is None and "edge_node_id" in self.model_fields_set:
            _dict['edge_node_id'] = None

        # set to None if hub_node_id (nullable) is None
        # and model_fields_set contains the field
        if self.hub_node_id is None and "hub_node_id" in self.model_fields_set:
            _dict['hub_node_id'] = None

        # set to None if external_asset_id (nullable) is None
        # and model_fields_set contains the field
        if self.external_asset_id is None and "external_asset_id" in self.model_fields_set:
            _dict['external_asset_id'] = None

        # set to None if parent (nullable) is None
        # and model_fields_set contains the field
        if self.parent is None and "parent" in self.model_fields_set:
            _dict['parent'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of TreeSystemElement from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "metadata": obj.get("metadata"),
            "signals": obj.get("signals"),
            "children": obj.get("children"),
            "is_root": obj.get("is_root"),
            "key": obj.get("key"),
            "topic": obj.get("topic"),
            "node_type": obj.get("node_type") if obj.get("node_type") is not None else 'system_element',
            "name": obj.get("name"),
            "description": obj.get("description"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "_normalized_name": obj.get("_normalized_name"),
            "_topic_context_section": obj.get("_topic_context_section"),
            "edge_node_id": obj.get("edge_node_id"),
            "hub_node_id": obj.get("hub_node_id"),
            "external_asset_id": obj.get("external_asset_id"),
            "lft": obj.get("lft"),
            "rght": obj.get("rght"),
            "tree_id": obj.get("tree_id"),
            "level": obj.get("level"),
            "parent": obj.get("parent")
        })
        return _obj


