
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Annotated, Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing_extensions import Self


class UpdateDataAcquisitionRequest(BaseModel):
    """
    UpdateDataAcquisitionRequest
    """ # noqa: E501
    context_id: StrictStr = Field(description="ULID of the DataTagContext to update. Get this from ListAvailableDataTags or BindDataTag.")
    is_logged: StrictBool | None = Field(default=None, description="Whether to log values to the historian database.")
    is_published: StrictBool | None = Field(default=None, description="Whether to publish values to the MQTT broker.")
    polling_rate_ms: Annotated[int, Field(le=3600000, strict=True, ge=100)] | None = Field(default=None, description="Custom polling interval in milliseconds. Set to null to use the connector's default rate.")
    __properties: ClassVar[list[str]] = ["context_id", "is_logged", "is_published", "polling_rate_ms"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of UpdateDataAcquisitionRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if polling_rate_ms (nullable) is None
        # and model_fields_set contains the field
        if self.polling_rate_ms is None and "polling_rate_ms" in self.model_fields_set:
            _dict['polling_rate_ms'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of UpdateDataAcquisitionRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "context_id": obj.get("context_id"),
            "is_logged": obj.get("is_logged"),
            "is_published": obj.get("is_published"),
            "polling_rate_ms": obj.get("polling_rate_ms")
        })
        return _obj


