
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing_extensions import Self


class User(BaseModel):
    """
    User
    """ # noqa: E501
    sub: StrictStr
    email: StrictStr
    first_name: StrictStr | None = None
    last_name: StrictStr | None = None
    avatar_alt_icon: StrictStr | None = Field(default=None, description="* `INITIALS` - Initials * `FRANZ` - Franz")
    ai_description: StrictStr | None = None
    initial_password: StrictStr | None = None
    locale: StrictStr | None = None
    is_demo_user: StrictBool | None = None
    __properties: ClassVar[list[str]] = ["sub", "email", "first_name", "last_name", "avatar_alt_icon", "ai_description", "initial_password", "locale", "is_demo_user"]

    @field_validator('avatar_alt_icon')
    def avatar_alt_icon_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['INITIALS', 'FRANZ']):
            raise ValueError("must be one of enum values ('INITIALS', 'FRANZ')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of User from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if ai_description (nullable) is None
        # and model_fields_set contains the field
        if self.ai_description is None and "ai_description" in self.model_fields_set:
            _dict['ai_description'] = None

        # set to None if locale (nullable) is None
        # and model_fields_set contains the field
        if self.locale is None and "locale" in self.model_fields_set:
            _dict['locale'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of User from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sub": obj.get("sub"),
            "email": obj.get("email"),
            "first_name": obj.get("first_name"),
            "last_name": obj.get("last_name"),
            "avatar_alt_icon": obj.get("avatar_alt_icon"),
            "ai_description": obj.get("ai_description"),
            "initial_password": obj.get("initial_password"),
            "locale": obj.get("locale"),
            "is_demo_user": obj.get("is_demo_user")
        })
        return _obj


