
"""
    PREKIT API

    PREKIT API Documentation

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Annotated, Any, ClassVar

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing_extensions import Self


class WebhookAuthZRequest(BaseModel):
    """
    WebhookAuthZRequest
    """ # noqa: E501
    client_id: StrictStr
    username: StrictStr | None = None
    mountpoint: StrictStr | None = None
    topic: StrictStr | None = None
    qos: Annotated[int, Field(le=2, strict=True, ge=0)] | None = None
    payload: Any | None = None
    topics: list[dict[str, Any]] | None = None
    peername: StrictStr | None = None
    properties: Any | None = None
    protocol: StrictStr | None = None
    typ: StrictStr | None = None
    retain: StrictBool | None = None
    dup: StrictBool | None = None
    __properties: ClassVar[list[str]] = ["client_id", "username", "mountpoint", "topic", "qos", "payload", "topics", "peername", "properties", "protocol", "typ", "retain", "dup"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of WebhookAuthZRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if username (nullable) is None
        # and model_fields_set contains the field
        if self.username is None and "username" in self.model_fields_set:
            _dict['username'] = None

        # set to None if mountpoint (nullable) is None
        # and model_fields_set contains the field
        if self.mountpoint is None and "mountpoint" in self.model_fields_set:
            _dict['mountpoint'] = None

        # set to None if payload (nullable) is None
        # and model_fields_set contains the field
        if self.payload is None and "payload" in self.model_fields_set:
            _dict['payload'] = None

        # set to None if peername (nullable) is None
        # and model_fields_set contains the field
        if self.peername is None and "peername" in self.model_fields_set:
            _dict['peername'] = None

        # set to None if properties (nullable) is None
        # and model_fields_set contains the field
        if self.properties is None and "properties" in self.model_fields_set:
            _dict['properties'] = None

        # set to None if protocol (nullable) is None
        # and model_fields_set contains the field
        if self.protocol is None and "protocol" in self.model_fields_set:
            _dict['protocol'] = None

        # set to None if typ (nullable) is None
        # and model_fields_set contains the field
        if self.typ is None and "typ" in self.model_fields_set:
            _dict['typ'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of WebhookAuthZRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "client_id": obj.get("client_id"),
            "username": obj.get("username"),
            "mountpoint": obj.get("mountpoint"),
            "topic": obj.get("topic"),
            "qos": obj.get("qos"),
            "payload": obj.get("payload"),
            "topics": obj.get("topics"),
            "peername": obj.get("peername"),
            "properties": obj.get("properties"),
            "protocol": obj.get("protocol"),
            "typ": obj.get("typ"),
            "retain": obj.get("retain"),
            "dup": obj.get("dup")
        })
        return _obj


